### ISSUE TITLE
Authentication failed for a Gmail account

### ISSUE THREAD

**Issue by zanot** [ddeboer/imap#109]
Hi everybody,

I was testing your library with my professional Office 365 account, it's working fine (at least, I can get a listing of all my emails).

But when I want to do some tests with my personal Gmail account (with exactly the same code), I get stuck with the error :
```Fatal error: Uncaught exception 'Ddeboer\Imap\Exception\AuthenticationFailedException' with message 'Authentication failed for user xxxx@gmail.com ...```

on the line :
```php
$connection = $server->authenticate( ... );
```
I checked my Gmail settings, IMAP enabled, "Less secure apps" turned on, ... I don't understand.
I was thinking, maybe it's because my password contains some "fancy" characters ( / , `, ' , and others) but Gmail always accepted it.

Do you have any idea? Thanks.

**Comment by zanot** [comment]
After some refreshes, and "On / Off / On / Off" for Less secure apps, it's working now...
Sorry for this useless issue. Have a good day!

**Comment by aginev** [comment]
For the people that have same issue here is the link for enabling the less secure apps for Gmail Accounts: https://www.google.com/settings/u/4/security/lesssecureapps

Keep in mind that Gmail Accounts with two step verification can not be used in that manner.

**Comment by Pream-webapps** [comment]
> For the people that have same issue here is the link for enabling the less secure apps for Gmail Accounts: https://www.google.com/settings/u/4/security/lesssecureapps
> 
> Keep in mind that Gmail Accounts with two step verification can not be used in that manner.

Can you please let me know how to get **two step verification** mail box

**Comment by Slamdunk** [comment]
> Keep in mind that Gmail Accounts with two step verification can not be used in that manner.

This is completely the opposite, with 2FA enabled, you can create app password which works with php IMAP, see https://support.google.com/mail/answer/185833
