### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by robertosanval** [ddeboer/imap#110]
Hello,

I'm getting this problem when do a `composer update`

```
  Problem 1
    - Installation request for ddeboer/imap dev-master -> satisfiable by ddeboer/imap[dev-master].
    - ddeboer/imap dev-master requires ext-imap * -> the requested PHP extension imap is missing from your system.
```

I'm using MAMP PRO with PHP 7.0.3 and IMAP library is installed.

I'll appreciate any help.

**Comment by robertosanval** [comment]
I've solved it doing a `composer update --ignore-platform-reqs`

I don't know why `composer` fails when looks for that requirement.

**Comment by juliettemijeon** [comment]
I have the same issue. I'm not using MAMP, I installed PHP and the extensions I needed with Homebrew. However the IMAP extension doesn't show when I do `php -m`.
I'm a bit at a loss what to do, should I install MAMP as suggested [here](http://stackoverflow.com/questions/33528803/add-imap-extension-to-php-on-osx-el-capitan), even if I don't want to use it?

**Comment by Kyslik** [comment]
`composer update --ignore-platform-reqs` works for me I am using brewed php 71.

**Comment by Slamdunk** [comment]
This seems a [Composer](https://github.com/composer/composer) issue: please open a new issue on its repository.

**Comment by aK0nshin** [comment]
For php v.7.1 use
sudo apt install php7.**1**-imap

**Comment by zabih-github** [comment]
Work for me solved error..  composer update --ignore-platform-reqs
