### ISSUE TITLE
Problem on production server

### ISSUE THREAD

**Issue by robertosanval** [ddeboer/imap#111]
I've my system working fine on my dev machine but I've an issue on my prod server.

I've the same PHP version on both and I'm completely sure that authentication data is correct.

Imap extension it's installed and activated on both machines.

I receive this error on prod server:
```
[Ddeboer\Imap\Exception\AuthenticationFailedException]
  Authentication failed for user my_user with error imap_open(): Couldn't ope
  n stream {localhost:143}
```

I've tried to do a `telnet localhost 143` and I can login without any problems.

Anybody know what's happening?

**Comment by robertosanval** [comment]
I've just solved it adding flag `/novalidate-cert`

**Comment by ddeboer** [comment]
In that case, the issue may be related to your server’s SSL configuration.

**Comment by dleger** [comment]
Thanks robertosanval, you saved my day
