### ISSUE TITLE
Move and Delete Message not working

### ISSUE THREAD

**Issue by pedrosoares** [ddeboer/imap#112]
The Move Message are creating a copy and Delete Message not work.

**Comment by artemevsin** [comment]
can you provide example?

**Comment by pedrosoares** [comment]
I fix the problem in my Fork.
https://github.com/pedrosoares/imap/blob/master/src/Message.php

**Comment by artemevsin** [comment]
There is Mailbox::expunge() method. You can use it like:

```
$mailbox = $this->connection->getMailbox('INBOX');
$mailboxTo = $this->connection->getMailbox('ARCHIVE');

$messages = $mailbox->getMessages();
foreach ($messages as $message) {
    $message->move($mailboxTo); //  or $message->delete();
}
$mailbox->expunge();
```

**Comment by pedrosoares** [comment]
True, work now, thanks. And about some type of attachments are not recognized from this issue: https://github.com/ddeboer/imap/issues/74? I fix this problem too in my Fork, if you wanna see, feel free.

**Comment by ddeboer** [comment]
Glad that you got it working! Please open a PR on this repository for the attachment issue.
