### ISSUE TITLE
Getting the Feedback Report Type

### ISSUE THREAD

**Issue by iadj** [ddeboer/imap#117]
Is it currently possible to get the `feedback:report-type`? It appears to be inside the protected `parts` property, but I can't find a function built in to access it.

**Comment by holdmann** [comment]
Can you attach origin of email message? 
I don't understand what you are trying to process.

**Comment by Slamdunk** [comment]
Hi, as asked by @holdmann, can you provide the raw message body (with sensitive data obscured) of such email?

**Comment by Slamdunk** [comment]
Closing due to unanswered updates.

Feel free to reopen the issue if needed.
