### ISSUE TITLE
ICS file not supported as attachment

### ISSUE THREAD

**Issue by scriptPilot** [ddeboer/imap#120]
First of all thank you for your simple and lightwight class :-)
I hope there will be a hotfix for the following issue ... 

If I receive a message with attached Outlook ICS file, I got the following error message:

`Fatal error: Uncaught exception 'Ddeboer\Transcoder\Exception\IllegalCharacterException' with message 'String "BEGIN:VCALENDAR PRODID:-//Microsoft Corporation//Outlook 14.0`

With imap_structure() I got the following information for that part:

`["type"]=>
  int(0)
  ["encoding"]=>
  int(3)
  ["ifsubtype"]=>
  int(1)
  ["subtype"]=>
  string(8) "CALENDAR"
  ["ifdescription"]=>
  int(1)
  ["description"]=>
  string(32) "Kalender von Max Mustermann.ics"
  ["ifid"]=>
  int(0)
  ["lines"]=>
  int(3109)
  ["bytes"]=>
  int(242446)
  ["ifdisposition"]=>
  int(1)
  ["disposition"]=>
  string(10) "attachment"
  ["ifdparameters"]=>
  int(1)
  ["dparameters"]=>
  array(4) {`

**Comment by Slamdunk** [comment]
Hi, can you provide the raw message body (with sensitive information obsuced) of such email?

**Comment by Slamdunk** [comment]
By the error message it seems this bug is resolved by https://github.com/ddeboer/imap/pull/196
