### ISSUE TITLE
Undefined offset 

### ISSUE THREAD

**Issue by poznet** [ddeboer/imap#123]
Sometimes  when trying to parse headers  i get  
PHP Notice:  Undefined offset: 6 in /var/www/antyspam/vendor/ddeboer/imap/src/Message/Part.php on line 221

shouldn't  be there any array_key_exists ?

**Comment by holdmann** [comment]
Try this - https://github.com/ddeboer/imap/pull/114/commits/c64d37e641884d3c5b0e270a18695631bd266644

**Comment by poznet** [comment]
Works  fine :) 
Should be pulled to master :P

:+1:

**Comment by Slamdunk** [comment]
Related to https://github.com/ddeboer/imap/pull/114

**Comment by Slamdunk** [comment]
Closed by https://github.com/ddeboer/imap/pull/197 thank you
