### ISSUE TITLE
Is there any simple way to get message from inbox haveing only message id ?

### ISSUE THREAD

**Issue by poznet** [ddeboer/imap#125]

**Comment by poznet** [comment]
Is there any simple way to get message  from inbox   haveing only  message id  ?

**Comment by Slamdunk** [comment]
`$mailbox->getMessage(123);` is enough.

**Comment by wujku** [comment]
@Slamdunk probably by <123@example.com>

**Comment by Slamdunk** [comment]
@wujku in that case:
```php
$messages = $mailbox->getMessages(
    new Ddeboer\Imap\Search\RawExpression(
        'HEADER Message-ID "<123@example.com>"'
    )
);
```
But it seems this kind of search is badly supported by the most imap client: I couldn't get it work with any of my own 🙍

**Comment by atifghaffar** [comment]
Hi, When I try it, I get the following
Fatal error: Uncaught Ddeboer\Imap\Exception\InvalidSearchCriteriaException: Invalid search criteria [HEADER Message-ID "<x18eNtboeRZUOZDK2rhuVhKuvZDdq3rzdEj4K9EQg@shocksend.pl>"] imap_alerts (0): imap_errors (1): - Unknown search criterion: HEADER in

**Comment by atifghaffar** [comment]
I finaly used the approach in https://bugs.php.net/bug.php?id=73640

		    new Ddeboer\Imap\Search\RawExpression(
		        sprintf('TEXT "Message-ID: %s"', $message_id)
		    )

**Comment by rvalitov** [comment]
@atifghaffar Unfortunately your approach does not work in my case with GMail. I always get an empty list of emails. Is there any other trick you did?

**Comment by ibraheem-ghazi** [comment]
Not working on GMail

**Comment by atifghaffar** [comment]
> @atifghaffar Unfortunately your approach does not work in my case with GMail. I always get an empty list of emails. Is there any other trick you did?

try with HEADER

	    new Ddeboer\Imap\Search\RawExpression(
	        sprintf('HEADER "Message-ID: %s"', $message_id)
	    )
