### ISSUE TITLE
strange behavior  with getMessages

### ISSUE THREAD

**Issue by poznet** [ddeboer/imap#127]
```
$messages =$mailbox->getMessages();  
echo count($messages) ;  //gives  100
$checked=0;

foreach($messages as $msg) {
  $checked++;
}
echo $checked;   //  always  gives 40 
```

why getMessages have 100 item ,and in foreach  only 40 are accessible  ?

**Comment by Slamdunk** [comment]
Hi, this behaviour seems weird: can you provide more infos about the IMAP server you are testing against?

For example, you can try to shrink the mailbox till the `count()` call gives 2 and the `foreach` gives 1, and then provide here (with sensitive data obscured) the two email raw bodies.

**Comment by Slamdunk** [comment]
Closing due to unanswered updates.

Feel free to reopen the issue if needed.
