### ISSUE TITLE
how to get sent messages?

### ISSUE THREAD

**Issue by pkoperkowsky** [ddeboer/imap#129]
Hello. How can I download all the messages in the threads and also messages sent.  Normally I get only messages received (or so that is gmail).

**Comment by Slamdunk** [comment]
Hi, it depends on the name of the send messages mailbox. For example my Gmail is localized, and running a simple script like this:
```php
$server = new Ddeboer\Imap\Server('imap.gmail.com');
$connection = $server->authenticate('my_email@gmail.com', 'my_password');

foreach ($connection->getMailboxes() as $mailbox) {
    var_dump($mailbox->getName());
}
```
Results in
```
string(5) "INBOX"
string(7) "[Gmail]"
string(13) "[Gmail]/Bozze"
string(15) "[Gmail]/Cestino"
string(21) "[Gmail]/Posta inviata"
string(12) "[Gmail]/Spam"
```
So to get the sent messages, you need to use that particular mailbox name:
```php
$messages = $connection->getMailbox('[Gmail]/Posta inviata')->getMessages();
```
