### ISSUE TITLE
Is there a method to turn a seen message into an "unseen" one ?

### ISSUE THREAD

**Issue by apa-oc** [ddeboer/imap#130]
Is there a method to turn a seen message into an "unseen" one ?

Many thanks !

A

**Comment by JohannLucas** [comment]
I'm trying to do this all day, if I do i'll post here. If somebody get this, please post here too.

**Comment by JohannLucas** [comment]
I tried do this in a gmail account and seems that isn't possible in gmail but I believe that is possible in a webmail account for example, try to do with this codes:

http://stackoverflow.com/questions/1604016/imap-in-php-marking-a-message-unread-unseen

http://stackoverflow.com/questions/12811520/marking-an-email-unread-in-php-imap

**Comment by wujku** [comment]
This feature was added in (#144).

@ddeboer For above pull request, Travis CI test throws that error (related with other Pull Requests):
```
Ddeboer\Imap\Tests\ConnectionTest exception 'RuntimeException' with message 'Please set environment variable EMAIL_USERNAME before running functional tests' in /home/travis/build/ddeboer/imap/tests/AbstractTest.php:18*
```

**Comment by Slamdunk** [comment]
Closing this in favour of #144
