### ISSUE TITLE
URGENT: The timezone could not be found in the database

### ISSUE THREAD

**Issue by lrpasquetto** [ddeboer/imap#135]
I have a client that has more than 20,000 emails, it keeps the server to control backups.
I'm riding a webmail for my clients and some messages when I read , accuses the following error:

`Exception in Headers.php line 56:
DateTime::__construct(): Failed to parse time string (Fri, 14 Mar 14 16:19:14 Hora oficial do Brasil) at position 24 (H): The timezone could not be found in the database`
- in Headers.php line 56
- at DateTime->__construct('Fri, 14 Mar 14 16:19:14 Hora oficial do Brasil') in Headers.php line 56
- at Headers->parseHeader('date', 'Fri, 14 Mar 14 16:19:14 Hora oficial do Brasil') in Headers.php line 23
- at Headers->__construct(object(stdClass)) in Message.php line 185
- **at Message->getHeaders() in Message.php line 170**
- at Message->getSubject() in HomeController.php line 179

**Comment by ddeboer** [comment]
That’s a weird timezone. Which mailserver produces those dates? 

What we could do, is wrap the DateTime construction in a try/catch.

**Comment by Slamdunk** [comment]
Hi @lrpasquetto can you provide the message raw headers (with sensitive data obscured) that produced the issue?

**Comment by Slamdunk** [comment]
@lrpasquetto We have added various weird date time format found in production email:
https://github.com/ddeboer/imap/blob/aac8f581d3e636a69002a367379cb3996c5a6a3d/tests/MessageTest.php#L302-L315

If you will ever get again the mail that produces the error we'll be happy to put it in the cases tested.
Until that time, I'm closing this stalled issue.
