### ISSUE TITLE
Mark messages

### ISSUE THREAD

**Issue by mikk150** [ddeboer/imap#139]
I cannot find any way to mark messages right now

It would be nice to be able to mark messages as unread and/or flagged

**Comment by serveriev** [comment]
`$message->getBodyHtml();` - set seen mark
`$message-->keepUnseen()->getBodyHtml()`  set unseen mark

**Comment by obeyer** [comment]
$message->getContent(); will set SEEN flag, 
getBodyHtml() doesn't do it

**Comment by Slamdunk** [comment]
Implemented in https://github.com/ddeboer/imap/pull/144 and https://github.com/ddeboer/imap/pull/203
