### ISSUE TITLE
getFrom() Not working for Gmail Inbox on Laravel 

### ISSUE THREAD

**Issue by rohan-krishna** [ddeboer/imap#150]
Hi,

I'm using this for fetching mails from Gmail ( GSuite Inbox ) on Laravel. I've already enabled Access for Low Security Apps on GSuite's account settings. 
I'm able to fetch *Subject* and *Message Body* but not *From Address* of the emails. Please help me with this.

**Comment by Slamdunk** [comment]
Hi, can you provide more details about this issue, for example the original email, the code you wrote and the actual results?

**Comment by Slamdunk** [comment]
Closing due to unanswered updates.

Feel free to reopen the issue if needed.
