### ISSUE TITLE
The library doesn't support using sort by

### ISSUE THREAD

**Issue by jqqjj** [ddeboer/imap#151]
I need to sort all messages in lists.

**Comment by jqqjj** [comment]
Resolution: use codes
"$messageNumbers = imap_sort($this->connection->getResource(),SORTDATE,1, \SE_UID, $query);"
replace 
"$messageNumbers = imap_search($this->connection->getResource(), $query, \SE_UID)" 
in line 63 in file Mailbox.php

**Comment by Slamdunk** [comment]
Implemented in https://github.com/ddeboer/imap/pull/213 thank you for the feedback
