### ISSUE TITLE
Regex in SearchExpressions

### ISSUE THREAD

**Issue by grobmeier** [ddeboer/imap#157]
Hi 

the lib is great! I could use some regex in searching. Like:

Currently:

```
$search = new SearchExpression();
$search->addCondition(new Subject("Test"));
```

Could be extended to:

```
$search = new SearchExpression();
$search->addCondition(new Subject("Test.*", true)); // true means RegEx = true
```

**Comment by Slamdunk** [comment]
Hi, what is now blocking you from using a regex like `new Subject('Test.*')`?

In the manual I see no reference to a special regex modifier:
https://secure.php.net/manual/en/function.imap-search.php

**Comment by Slamdunk** [comment]
A `Ddeboer\Imap\Search\RawExpression` condition has been implemented in https://github.com/ddeboer/imap/pull/198: you can now write custom criteria.
