### ISSUE TITLE
Get raw message

### ISSUE THREAD

**Issue by RikudouSage** [ddeboer/imap#161]
Hello, I didn't find any way to get the raw message output, can you add it?

It's easy, you just omit the `$section` parameter of `imap_fetchbody()` and it fetches the whole raw e-mail.

**Comment by Lewiscowles1986** [comment]
I added the following to `src/Message/Part.php`

```php
    public function getRAW() {
      return imap_fetchbody(
        $this->stream,
        $this->messageNumber,
        null,
        \FT_PEEK
      );
    }
```

seems to work and it's pretty fast. @Slamdunk, would this help with the tracking down of problems?

**Comment by Slamdunk** [comment]
Yes: can you add test and creare a PR?

**Comment by Lewiscowles1986** [comment]
Looks like it'll need a few. Already seeing this in logs...

```
PHP Warning:  imap_fetchbody(): Bad message number in /projects/CODESIGN2/email-harvest/vendor/ddeboer/imap/src/Message/Part.php on line 334
PHP Stack trace:
PHP   1. {main}() /projects/CODESIGN2/email-harvest/harvest.php:0
PHP   2. Ddeboer\Imap\Message\Part->getRAW() /projects/CODESIGN2/email-harvest/harvest.php:34
PHP   3. imap_fetchbody() /projects/CODESIGN2/email-harvest/vendor/ddeboer/imap/src/Message/Part.php:334
```

**Comment by Lewiscowles1986** [comment]
I'm beginning to worry that a lot of my problems are with my mail host...

**Comment by Lewiscowles1986** [comment]
Does this get the entire message body including attachments?

**Comment by Slamdunk** [comment]
Implemented in https://github.com/ddeboer/imap/pull/146
