### ISSUE TITLE
Image inline was not shown, but was saved as attachment

### ISSUE THREAD

**Issue by adityaprawira** [ddeboer/imap#164]
hi your library is perfect

but i got one problem

how can i display inline images in email body and not saved as attachment ?

thank you

**Comment by Slamdunk** [comment]
Hi, inline images in emails are always handled as attachments by most email clients, and are available through the `$message->getAttachments()` API.

I don't get what you mean by `display inline images`: this library doesn't provide any feature about displaying email contents.

**Comment by Slamdunk** [comment]
Closing due to unanswered updates.

Feel free to reopen the issue if needed.
