### ISSUE TITLE
Any new release soon?

### ISSUE THREAD

**Issue by HawkonDK** [ddeboer/imap#166]
Any new release soon or will it stay in pre-release in a long time ?

**Comment by Slamdunk** [comment]
I'll help @ddeboer from now maintaining this library, keep tracking us, I think we'll release a stable version soon. You can take a look at our start point: https://github.com/ddeboer/imap/pull/170

**Comment by artemevsin** [comment]
Hi guys, glad to see there is some activity now. We use this package in one project. I though this package is not maintained anymore. Anyway if you will need any kind of help with maintaining, please contact me, I will happy to help you.
