### ISSUE TITLE
Error when trying fetch messages from container

### ISSUE THREAD

**Issue by micrarior** [ddeboer/imap#167]
`imap_getmailboxes` returns also mailbox container.  It needs additional attributes check for LATT_NOSELECT according to [documentation](https://secure.php.net/manual/en/function.imap-getmailboxes.php)

Gmail as example
`PHP Fatal error:  Uncaught ErrorException: Unknown: [NONEXISTENT] Unknown Mailbox: [Gmail] (now in authenticated state)
(Failure) (errflg=2) in Unknown:0`

**Comment by Slamdunk** [comment]
With the feature implemented in https://github.com/ddeboer/imap/pull/184 you can now get mailbox attributes by calling `$mailbox->getAttributes()`, so you can skip continer mailboxes with a code like:
```php
if ($mailbox->getAttributes() & \LATT_NOSELECT) {
    // skip this mailbox
}
```
Thank you for the feedback.
