### ISSUE TITLE
Date format for date search condition

### ISSUE THREAD

**Issue by micrarior** [ddeboer/imap#168]
Date format must be `d-M-Y` according to formal syntax of the [rfc2060](http://www.faqs.org/rfcs/rfc2060.html)

**Comment by Slamdunk** [comment]
Hi, can you pinpoint where the library use or outputs a malformed date?

**Comment by micrarior** [comment]
https://github.com/ddeboer/imap/blob/b1939740d62e427a8105312a3fb574deb62dcf68/src/Search/Date/AbstractDate.php#L18

**Comment by Slamdunk** [comment]
Fixed with https://github.com/ddeboer/imap/pull/189, thank you very much for your help.
