### ISSUE TITLE
Failed to install using composer - PHP7

### ISSUE THREAD

**Issue by HawkonDK** [ddeboer/imap#169]
```
Using version ^0.5.2 for ddeboer/imap
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ddeboer/imap ^0.5.2 -> satisfiable by ddeboer/imap[0.5.2].
    - ddeboer/imap 0.5.2 requires ext-imap * -> the requested PHP extension imap is missing from your system.


Installation failed, deleting ./composer.json.
```

The weird thing is, that PHP have imap installed.

**Comment by ddeboer** [comment]
I can install the library on PHP 7 (Homebrew on Mac) without trouble. What does `php -i | grep imap` show?

**Comment by HawkonDK** [comment]
`Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, smb, smbs, smtp, smtps, telnet, tftp`

Btw where is this file??
Transcoder.php

**Comment by artemevsin** [comment]
Probably you should enable imap extension for php in cli mode. You can check if extension is enabled with `php -m` command. If imap is not in the list, check if its enable in php.ini file, that is used for PHP CLI mode `php --ini`. You did not say, what OS you use, but in debian you should see something like `/etc/php/7.1/cli/conf.d/20-imap.ini` in `php --ini` output. However in one of these files you should find line `extension=imap.so`. If not, just add this line to php.ini.

As workaround you could tell composer, that you have installed imap extension with config section in composer.json. You should put there something like this:

```json
 "name": "myapp",
  "config": {
    "platform": {
      "php": "7.1",
      "ext-imap": "2007f"
    }
  },
```
Btw - Transcoder.php is part of ddeboer/transcoder that is dependency of ddeboer/imap

**Comment by Slamdunk** [comment]
As wrote by @artemevsin composer is clear about the `imap` missing extension:
```
    - ddeboer/imap 0.5.2 requires ext-imap * -> the requested PHP extension imap is missing from your system.
```
You need to install it in order to use this library.

**Comment by HawkonDK** [comment]
well my computer doesn't have imap extension but my local web host have

**Comment by Slamdunk** [comment]
This seems an issue related to [Composer](https://github.com/composer/composer) rather than this library: you can ask help there, they have more knowledge about this topic.

**Comment by HawkonDK** [comment]
hmm sounds right, then I just copy your composer.json and change it
