### ISSUE TITLE
getHeaders() decode broke information

### ISSUE THREAD

**Issue by HawkonDK** [ddeboer/imap#171]
in the code (Headers.php):

```
61    case 'cc':
62    $emails = [];
63    foreach ($value as $address) {
64        $emails[] = $this->decodeEmailAddress($address);
65    }
66            
67    return $emails;
68    case 'subject':
69         return $this->decode($value);
70    default:
71         return $value;
```

`$this->decode($value)` at line 69 broke the subject and return a empty string

**Comment by Slamdunk** [comment]
The `decode` function is under investigation, but we need test cases to add to our test suite: can you provide the raw message headers of the email that caused your error?

**Comment by HawkonDK** [comment]
Okay so today I just change my own code and now it don't become mad over the decode(). Why I don't know, nothing make sens, but the important is that it works

**Comment by Slamdunk** [comment]
Thank you for your feedback, the issue has been fixed in https://github.com/ddeboer/imap/pull/196
