### ISSUE TITLE
need a getPersonal()

### ISSUE THREAD

**Issue by HawkonDK** [ddeboer/imap#179]
the code need a getPersonal()  

Example

```
public function getPersonal() : string
{	
     $sender = $this->getHeaders()->get('sender');
     $result = json_decode(json_encode($sender), true);
    
     return imap_utf8($result[0]['personal']);
}
```

**Comment by Slamdunk** [comment]
Hi, we can implement a getSender api, but what is the need to pass through the json encoding and decoding?

**Comment by HawkonDK** [comment]
don't think it's necessary to use json encoding. haven't study all the code yet so it was just a quick way to get it work

**Comment by HawkonDK** [comment]
Oh btw is there a way to reverse the output of `getMessages()` ??

**Comment by Slamdunk** [comment]
Closing due to unanswered updates.

Feel free to reopen the issue if needed.
