### ISSUE TITLE
Implement security

### ISSUE THREAD

**Issue by HawkonDK** [ddeboer/imap#180]
mails may contain malicious code that may harm one's web host, so I feel that there must be built-in security to take care of basic, maybe more, so the user of this projects don't get attacks by the most used attacks

Don't think we can protect users from links, but maybe files and scripts

**Comment by Slamdunk** [comment]
This is out of this library scope, sorry.

**Comment by HawkonDK** [comment]
not even <script> protection ?

**Comment by Slamdunk** [comment]
No because, it depends on the way you display it, and it's not a part of this library scope.
