### ISSUE TITLE
Potential memory issue with attachments

### ISSUE THREAD

**Issue by doublehops** [ddeboer/imap#195]
I seem to be running out of memory when the library downloads attachments greater than 500KB. How does the library handle memory? Is there a need or a way to clear the attachment from memory once a document has been saved locally? I'm not sure how to debug this issue at this time.

**Comment by Slamdunk** [comment]
We'll try to reproduce the error as soon we finish the encoding refactor.
In the meantime, can you try to:

1. Cycle through a bunch emails, sorted from smaller to larger, and output the memory consuption each step
1. Post here the full error stack when it occurs

Please?

**Comment by doublehops** [comment]
Thanks for the reply, I'll do this over the weekend. I should have mentioned that when the documents are saved to the hard disk, they are being converted to images (with convert) and having tesseract OCR the images. It could be any of these scripts that are causing memory issues but I'm trying to find the best way to isolate them and determine which is using the memory. Possibly htop will help me with this.

**Comment by Lewiscowles1986** [comment]
@doublehops I've backed up a few GB of emails with attachments varying from 5kb to 27MB (which is a stupid size of attachment). I've not noticed it blowing up RAM.

**Comment by doublehops** [comment]
Thanks for the quick response and effort and thanks for creating the library.

**Comment by Slamdunk** [comment]
No problem. For now I'm going to close the issue: if you ever face the problem again and you can provide an example, ping me
