### ISSUE TITLE
Need getAll for headers

### ISSUE THREAD

**Issue by Lewiscowles1986** [ddeboer/imap#200]
Because `Headers` and parent class `Parameters` are not `Iterable` it's impossible to get headers if you don't know what the headers are.

Also in some cases, it would be more useful to return all headers within an array than to iterate over them (cost of copy vs iteration where copy or filter would be implemented)

**Comment by Slamdunk** [comment]
Implemented in https://github.com/ddeboer/imap/pull/215 thank you for the feedback
