### ISSUE TITLE
getBodyText() returns nothing

### ISSUE THREAD

**Issue by lgg** [ddeboer/imap#251]
code:
```
echo "html: ".$message->getBodyHtml()."\n";
echo "text: ".$message->getBodyText()."\n";
```

outgoing:
```
html: Вам пришла СМС<br/>От: <br/>На номер: <br/><br/>Cообщение: Тест^M

text:
```

**Comment by Slamdunk** [comment]
Hi, if the email doesn't contain any `text/plain`, it is the right behaviour.
Can you paste the entire raw message?

**Comment by lgg** [comment]
@Slamdunk oh, sorry. It wasn't obvious from docs that it returns text content only if it presents, i thought that it converts content to text and return it anyway.
