### ISSUE TITLE
[TypeError] Return value of Ddeboer\Imap\Message\AbstractMessage::getId() must be of the type string, null returned

### ISSUE THREAD

**Issue by wujku** [ddeboer/imap#253]

**Comment by Slamdunk** [comment]
Hi, can you provide the full error stack?

**Comment by wujku** [comment]
@Slamdunk occurred in production ;-)

**Comment by Slamdunk** [comment]
I guess the email doesn't have a Message-ID header, is it?

**Comment by wujku** [comment]
Yes

**Comment by Slamdunk** [comment]
Yes the email has the header or yes it doesn't? :D

**Comment by wujku** [comment]
@Slamdunk :D 
Yes it does not.

**Comment by Slamdunk** [comment]
Closed by #254

**Comment by Slamdunk** [comment]
Released in [1.0.8](https://github.com/ddeboer/imap/releases/tag/1.0.8)
