### ISSUE TITLE
Compare to fetch library

### ISSUE THREAD

**Issue by piernik** [ddeboer/imap#258]
I was using https://github.com/tedious/Fetch
I'm making new version of my app and found Your solution. 
Can You compare Your solution to `fetch` ?

I see that You have updates which is great.

**Comment by Slamdunk** [comment]
For the record there is a third library that has the same spread: https://github.com/barbushin/php-imap

| Repo | Downloads | Latest commit (as of 2017-11-06) |
| --- | --- | --- |
| [barbushin/php-imap](https://github.com/barbushin/php-imap) | [![Total Downloads](https://poser.pugx.org/php-imap/php-imap/downloads)](https://packagist.org/packages/php-imap/php-imap) |  17 days ago |
| [tedious/Fetch](https://github.com/tedious/Fetch) | [![Total Downloads](https://poser.pugx.org/tedivm/fetch/downloads)](https://packagist.org/packages/tedivm/fetch) | 1 year ago |
| [ddeboer/imap](https://github.com/ddeboer/imap) | [![Total Downloads](https://poser.pugx.org/ddeboer/imap/downloads)](https://packagist.org/packages/ddeboer/imap) | Today |

Two months ago I had to choose for my business an IMAP library.

tedious/Fetch was promising, but with no test on PHP 7 and unmaintained.

barbushin/php-imap is well supported by maintainers and community, it handles a lot of edge cases, but lacks tests.

ddeboer/imap focuses on object-oriented programming, is (almost) all tested and, most important to me, it's completely [mockable](https://github.com/ddeboer/imap#mock-the-library), so it's easy to test your app against it.

**Comment by piernik** [comment]
Thanks. I'll choose Your library.
If I have any sugestion I'll post an issue ;)

**Comment by Slamdunk** [comment]
> If I have any sugestion I'll post an issue ;)

They'd be very appreciated 👍
