### ISSUE TITLE
Supporting imap_append

### ISSUE THREAD

**Issue by piernik** [ddeboer/imap#259]
I'm testing Your library and I must say it's doing ok.
Do You have support for `imap-append` to put send email to propper folder?

**Comment by Slamdunk** [comment]
Yes, it's not a common requested featuer, but has it:

https://github.com/ddeboer/imap/blob/3680d0074d94314b9666c93bf3816673ac6e57bc/src/Mailbox.php#L208-L218

**Comment by piernik** [comment]
Great!
