### ISSUE TITLE
Implement imap_timeout

### ISSUE THREAD

**Issue by piernik** [ddeboer/imap#260]
I think supporting `timeout` (http://php.net/manual/en/function.imap-timeout.php) for  `Server` would be great.

**Comment by Slamdunk** [comment]
Related to https://github.com/ddeboer/imap/issues/90

**Comment by piernik** [comment]
I know. I'm using it right now but it could be implemented

**Comment by Slamdunk** [comment]
The fact is that: in which class should we put it?

If we put it in [Imap\Server](https://github.com/ddeboer/imap/blob/1.1.0/src/Server.php), a user could think that, having two server instances, you can change the timeouts for a server and not for the other, and that would be false.

The only implementation with a meaning would be a new class with a static method that would do exactly the same as calling `imap_timeout` directly.

**Comment by piernik** [comment]
You're right - it is global setting. 
You can change timeout before calling mail server and revert it afterwards.
Or You can simply only mention about it in readme.
Or do nothing .... ;)

**Comment by Slamdunk** [comment]
Closed by #263
