### ISSUE TITLE
Embeded image - cid :/

### ISSUE THREAD

**Issue by piernik** [ddeboer/imap#269]
[inline.zip](https://github.com/ddeboer/imap/files/1490867/inline.zip)

I have eml (inline.zip) file that has embeded image but using `getBodyHtml` leaves `cid:` - I think it should paste base64 version.
I also tried to use `isEmbeddedMessage()` for attachement but it is not set.
How to get content with encoded img not cid?

**Comment by Slamdunk** [comment]
Hi, the behaviour you describe is correct. The purpose of this library is to report a message that you can interact with in an OOP way. Interpreting or altering it shall not be done by this library.

It is also correct that `isEmbeddedMessage` returns false, is it not an embedded message.
What you can get is the image attachment.

It is up to the user to interpret or display the message.

**Comment by piernik** [comment]
Why not providing library that doeas it all?
I'm creating method that puts inline images to html. 
Here it is. I can make new PR for it - want to?

```php
final public function getBodyHtmlEmbededImages()
    {
        $body = $this->getBodyHtml();
        if ($attachments = $this->getAttachments()) {
            foreach ($attachments as $attachment) {
                $structure = $attachment->getStructure();
                if ($structure->id != '') {
                    $body = str_replace(
                        '"cid:' . str_replace(['<', '>'], '', $structure->id) . '"',
                        '"data:' . $attachment->getType() . '/' . $attachment->getSubtype() . ';' . $attachment->getEncoding() . ',' . $attachment->getContent() . '"',
                        $body
                    );
                }
            }
        }

        return $body;
    }
```

**Comment by Slamdunk** [comment]
> Why not providing library that does it all?

Because the functionality you are requesting/proposing is tightened to a very specific context, that falls outside this library purpose.

The goal of this library is to read and process e-mails over IMAP. What the user does after these two steps should not be part of the library.

Keeping the library small and single-purpose ease the maintainance and reduce the likelyhood of bugs and incompatibilities.

But feel free to create your own extensions to this library that provides the functionalities you are proposing.

**Comment by piernik** [comment]
:/ It's only one extra method. It's Your lib though

**Comment by Slamdunk** [comment]
It's not just an extra method.

It's a new functionality that must be tested and matinained, and that should have a meaning in the context it would belong to.

By the way you should be able to achieve what you want smoothly using the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern).
