### ISSUE TITLE
Create a Wiki page

### ISSUE THREAD

**Issue by HawkonDK** [ddeboer/imap#272]
Please create a wiki page where all documentation can be, the community can help update it

**Comment by Slamdunk** [comment]
There already is the [README.md](https://github.com/ddeboer/imap/blob/master/README.md) file, everyone can create a pull request asking to update it, and is automatically shipped everywhere in the distribution files.

Github Wikis are not bundled with the source code and tightened to Github; on the other hand documentation into the source code is easier to maintain and to be edited everywhere by anyone.

**Comment by HawkonDK** [comment]
I know, just that a Wiki page could contain more detailed descriptions and cover more

**Comment by Slamdunk** [comment]
Thank for the suggestion; at the time beeing we are not intended to change the documentation format.

Feel free to PR improvements to the README.md though.
