### ISSUE TITLE
markAsSeen was removed?

### ISSUE THREAD

**Issue by fatihunal** [ddeboer/imap#274]
Hi there,

markAsSeen was removed?
And i cant find setFlag function.
Is that removed?

**Comment by Slamdunk** [comment]
> markAsSeen was removed?

No, it's still there:
https://github.com/ddeboer/imap/blob/b9bbf40dc6751e21bea893870a29b0753c1ced02/src/Message.php#L220-L228

> And i cant find setFlag function.
> Is that removed?

Still there too:
https://github.com/ddeboer/imap/blob/b9bbf40dc6751e21bea893870a29b0753c1ced02/src/Message.php#L279-L293

**Comment by wujku** [comment]
@fatihunal also you can use `setFlag` method for `Mailbox` class (bulk changes):
https://github.com/ddeboer/imap/blob/b9bbf40dc6751e21bea893870a29b0753c1ced02/src/Mailbox.php#L125

**Comment by fatihunal** [comment]
Im sorry for this. Maybe its about package versions.

v1.1.2 requires php ^7.0

Im using PHP 5 and package version is v0.5.2. I will try install v1.1.2 and then check it.

Thanks for your patience.

**Comment by Slamdunk** [comment]
Yup, PHP < 7.0 is not supported anymore.
