### ISSUE TITLE
Appending mail with options

### ISSUE THREAD

**Issue by piernik** [ddeboer/imap#279]
You have `addMessage` method which appends mail to mailbox.
`imap_append` has `options` param: https://secure.php.net/manual/en/function.imap-append.php
With it We can mark appended mail as ex. `\Seen` which is very useful for appending mails to `sent` mailbox.
Can You provide second params which be the same as `option` param form `imap_append`?

**Comment by Slamdunk** [comment]
https://github.com/ddeboer/imap/pull/280

**Comment by Slamdunk** [comment]
Released in [1.2.0](https://github.com/ddeboer/imap/releases/tag/1.2.0)
