### ISSUE TITLE
Mailbox::getAttributes() does not exist + other issues

### ISSUE THREAD

**Issue by IhariR** [ddeboer/imap#285]
Method getAttributes() on Mailbox class mentioned in example does not exist ?

Environment variables are mentioned as IMAP_XXX in doc but appear to be EMAIL_XXX upon usage. Such as EMAIL_USERNAME instead of IMAP_USERNAME, etc.

AbstractTest and ServerTest have "imap.gmail.com" hardwired, which makes them fail when using another non-Gmail server. Same for the default port "993" and the default flags. Correcting the above environment variables, adding another for the flags and using these variables in the test code solve the issue.

imap\tests\MessageTest::testKeepUnseen() always fails for us, maybe because of the non-Gmail server (Exim4 on Debian).

**Comment by Slamdunk** [comment]
I think you are running an old version of this library, because:

> Method getAttributes() on Mailbox class mentioned in example does not exist ?

Yes, it's there:
https://github.com/ddeboer/imap/blob/43e88f17f4c0ee57f06ddc4ad78b82a1132a8cc3/src/Mailbox.php#L76-L84

> Environment variables are mentioned as IMAP_XXX in doc but appear to be EMAIL_XXX upon usage. Such as EMAIL_USERNAME instead of IMAP_USERNAME, etc.

The used variable are IMAP_* as shown in the code:
https://github.com/ddeboer/imap/blob/43e88f17f4c0ee57f06ddc4ad78b82a1132a8cc3/tests/AbstractTest.php#L35-L40

> AbstractTest and ServerTest have "imap.gmail.com" hardwired, which makes them fail when using another non-Gmail server. Same for the default port "993" and the default flags. Correcting the above environment variables, adding another for the flags and using these variables in the test code solve the issue.

Only environment variables are used, no hardcoded parameters in [ServerTest](https://github.com/ddeboer/imap/blob/1.2.0/tests/ServerTest.php) and [AbstractTest](https://github.com/ddeboer/imap/blob/1.2.0/tests/AbstractTest.php)

> imap\tests\MessageTest::testKeepUnseen() always fails for us, maybe because of the non-Gmail server (Exim4 on Debian).

Please update the library and retry

**Comment by IhariR** [comment]
Indeed my version was 0.5.2 while latest is 1.2.0. A git clone gives the 1.2.0 version, and shows you are right on the features.

I installed using the recommended way with "$ composer require ddeboer/imap" and this installed "^0.5.2" for me. It turns out that it was because my command-line PHP was version 5.6 and highest compatible version was the 0.5.2. After switching to PHP 7.0 for the CLI and updating composer.json to "~1.0" to lift the version limit, I was able to upgrade to 1.2.0.

Shouldn't the Composer install instructions be updated to warn that install will proceed for PHP less than 7.0, but would install an old version ? Or is this considered common sense enough ?

**Comment by Slamdunk** [comment]
> Or is this considered common sense enough ?

Indeed. We could in theory have 10 versions that support 10 different PHP version: it is up to the user to check what can be installed.
The link in the packagist site helps with that, clearly showing the requirements for the latest version:
https://packagist.org/packages/ddeboer/imap

**Comment by IhariR** [comment]
Fair enough ; thanks
