### ISSUE TITLE
Is there a way to get recent 100 messages.

### ISSUE THREAD

**Issue by skooperss** [ddeboer/imap#287]
I am new to this . I want to know how to get recent 100 messages and how to check if there is new message arrived?

**Comment by skooperss** [comment]
any one here to help me in this?

**Comment by Slamdunk** [comment]
I'll reply on the next days, this is a project maintained in our spare time, please be patient.

**Comment by Slamdunk** [comment]
> I am new to this . I want to know how to get recent 100 messages

To get the messages of the last 30 days you can search by date and sort by it:
```php
$today = new DateTimeImmutable();
$lastMonth = $today->sub(new DateInterval('P30D'));

$messages = $mailbox->getMessages(
    new Ddeboer\Imap\Search\Date\Since($lastMonth),
    \SORTDATE, // Sort criteria
    true // Descending order
);
```
If you want the last 100 messages you can stop the iterator at the 100th message:
```php
$messages = $mailbox->getMessages(
    null, // No filter
    \SORTDATE, // Sort criteria
    true // Descending order
);

$index = 0;
foreach ($messages as $message) {
    ++$index;
    if ($index > 100) {
        break;
    }
    
    var_dump($message->getId());
}
```

> and how to check if there is new message arrived?

You can use the `Mailbox::getStatus()` method:
https://github.com/ddeboer/imap/blob/7adce46e1eb9e174669e3cb1df90e2c3c849022c/src/Mailbox.php#L106-L116
That proxy to the native [imap_status](https://secure.php.net/manual/en/function.imap-status.php) PHP function.

And also you can get those recent messages with a specific filter:

```php
$messages = $mailbox->getMessages(
    new Ddeboer\Imap\Search\Flag\Unseen(),
);
```
