### ISSUE TITLE
Error Content-ID: <<

### ISSUE THREAD

**Issue by piernik** [ddeboer/imap#292]
I'm handling lots of different accounts so I don't know if it is a bug or wierd email but I have something like this:
```
--_EFCD9C7B-E8A3-40DB-9289-6DFE606EA17E_
Content-Type: image/png; name="image001.png"
Content-ID: <<image001.png@01D37006.B013AAF0>>
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="image001.png"
```

It should be `Content-ID: <image001.png@01D37006.B013AAF0>`

Can You check if You don't have a bug?
Sadly I don't have access to this mail account so I cannot fetch `eml` file from other software. I have only `eml` file from Your `fetcher`.

**Comment by Slamdunk** [comment]
Hi, this library doesn't alter the header nor the content of the email, and doesn't validate it neither.

If you use the `Message\Attachment::getStructure()` API you'll see that the Content-ID is present and represented exactly like it is in the email, valid or not.

**Comment by piernik** [comment]
I'm fetching email contents with `getRawMessage`

**Comment by Slamdunk** [comment]
The answer is the same: this library doesn't alter the content of the message.

**Comment by piernik** [comment]
Ok. Thanks.
