### ISSUE TITLE
Invalid Date header found: "Thur, 04 Jan 2018 06:44:23 +0400"

### ISSUE THREAD

**Issue by plehanov** [ddeboer/imap#293]
I run command 
/** @var Message $message */
$date = $message->getDate();

throw Exception with message -  Invalid Date header found: "Thur, 04 Jan 2018 06:44:23 +0400"

version - 1.1.2

**Comment by Slamdunk** [comment]
Released in [1.2.1](https://github.com/ddeboer/imap/releases/tag/1.2.1)
