### ISSUE TITLE
Attachment Mime Type

### ISSUE THREAD

**Issue by danr1979** [ddeboer/imap#295]
Hi.

Is it possible to get a string representation of the mime type of attachments?  I've had a look through the docs and code but have only found the getType() method that simply returns "application" rather than a full mime type.

Many thanks.

Dan

**Comment by Slamdunk** [comment]
Hi, there is also the `getSubtype()` API:
https://github.com/ddeboer/imap/blob/1113f9a3a34a311052739955d5b6081df588f862/src/Message/PartInterface.php#L54-L59
To complete the mimetype string. Concatenating the two you can get the mimetype specificed in the raw email.

If the email doesn't provide the explicit mimetype, no auto-guessing mechanism is provided by this library.

**Comment by danr1979** [comment]
Hi.  

I did try the getSubtype() but it didn't give the value I expected but it may be that the email didn't specify the mime type properly.  

Thanks for your help anyhow.
