### ISSUE TITLE
Attachment->getFilename return null

### ISSUE THREAD

**Issue by plehanov** [ddeboer/imap#297]
This method return null. Attachment present with name. 
Attachment parameters contain only boundary.

(array)$attachment->getParameters() = {array} [1]
 boundary = "=_743251f7a933f6b30c004fcb14eabb57"

`final class Attachment extends AbstractPart implements AttachmentInterface
{
    public function getFilename()
    {
        return $this->getParameters()->get('filename')
            ?: $this->getParameters()->get('name');
    }`

**Comment by Slamdunk** [comment]
Hi, we need the original raw email (with sensitive data omitted), may you post it here?

**Comment by plehanov** [comment]
@Slamdunk I can send it or tell him how to get a raw please.

**Comment by Slamdunk** [comment]
Send me it to: zoeslam at gmail dot com

**Comment by plehanov** [comment]
@Slamdunk I've posted. Thank you)

**Comment by Slamdunk** [comment]
Hi, I think that forwarding me the message changed the content.
If you are using GMail as client, please follow these instructions on how to save the email as an EML file, and then upload it here please:
https://www.lifewire.com/save-an-email-as-an-eml-file-in-gmail-1171956

**Comment by plehanov** [comment]
@Slamdunk i send eml file on your mail.

**Comment by Slamdunk** [comment]
Fix released in [1.2.2](https://github.com/ddeboer/imap/releases/tag/1.2.2), thanks.
