### ISSUE TITLE
$part->type can be 9

### ISSUE THREAD

**Issue by Denitz** [ddeboer/imap#301]
Reading messages from Gmail, see error:

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined offset: 9'
in /vendor/ddeboer/imap/src/Message/AbstractPart.php:458
```

`$part->type` is `9` and there is no such value in `AbstractPart::$typesMap`

**Comment by Slamdunk** [comment]
Fix released in [1.2.3](https://github.com/ddeboer/imap/releases/tag/1.2.3), thanks.
