### ISSUE TITLE
How to skip certificate validation?

### ISSUE THREAD

**Issue by lopolla** [ddeboer/imap#303]
I get errors on and it is probably my mistake. I am unsure how to fill in the fields below. Can someone help me out. The imap-server is my own SSL-server. But I think I would like to not validate SSL-cert.

```php
$parameters = '/novalidate-cert';
$server = new Server(
    'localhost', // required
    '993',     // defaults to '993'
    '???',    // defaults to '/imap/ssl/validate-cert'
    $parameters
);

// $connection is instance of \Ddeboer\Imap\Connection
$connection = $server->authenticate('myusername', 'mypassword');

```
Hope someone can help me :)

**Comment by Slamdunk** [comment]
Hi, this is a wrapper to the native functions of php imap extension, so you can always look at the native documentation.
In your case, take a look at: https://secure.php.net/manual/en/function.imap-open.php
Try using this flag: `/imap/ssl/novalidate-cert`

**Comment by lopolla** [comment]
Thanks for your reply. My first problem is that when running the code as shown it makes errors. So I must do something wrong. So I just basicly need something to run and not make an error :)
Can you see what might be wrong in the code?

**Comment by Slamdunk** [comment]
Flags is the third argument, not fourth. Try:
```php
$server = new Server(
    'localhost',
    '993',
    '/imap/ssl/novalidate-cert'
);
```

**Comment by oorwinlabs** [comment]
Working fine..thanks a lot !!

**Comment by oorwinlabs** [comment]
> Flags is the third argument, not fourth. Try:
> 
> ```
> $server = new Server(
>     'localhost',
>     '993',
>     '/imap/ssl/novalidate-cert'
> );
> ```

Working..Thx
