### ISSUE TITLE
feature: Bulk move

### ISSUE THREAD

**Issue by particleflux** [ddeboer/imap#305]
A bulk move feature would be great.

The php imap extension can do this: http://php.net/manual/de/function.imap-mail-move.php

Moving many emails one by one takes so much longer. Speaking of this, it would also be nice to have a possibility to get a list of message ids of a search query instead of an iterator.

**Comment by Slamdunk** [comment]
Would yoy like to create a PR for such features?

**Comment by particleflux** [comment]
PR created. 

As for the list of message ids, I noticed one can just use the `ArrayIterator::getArrayCopy()` method.
