### ISSUE TITLE
Class 'Ddeboer\Imap\Server' not found

### ISSUE THREAD

**Issue by BenjaminHoegh** [ddeboer/imap#314]
I get this when I install it using Composer and then follow the setup guide `Fatal error: Uncaught Error: Class 'Ddeboer\Imap\Server' not found`

Btw how to install it on a computer there doesn't have PHP mail extension but using Mamp to run the web server which have

**Comment by Slamdunk** [comment]
> I get this when I install it using Composer and then follow the setup guide Fatal error: Uncaught Error: Class 'Ddeboer\Imap\Server' not found

Hi, this library follows the Composer defaults behaviour: we can't help any further about this.

> Btw how to install it on a computer there doesn't have PHP mail extension

[imap](https://secure.php.net/manual/en/book.imap.php) extension is mandatory for this library

**Comment by BenjaminHoegh** [comment]
> imap extension is mandatory for this library

Yes, I know. the problem is that my PHP isn't the one the computer use, so when I start my local web server it have the IMAP extension but composer still look at the computers default PHP.

**Comment by BenjaminHoegh** [comment]
Well installed PHP on windows and installed it that way, now I can go back to macOS 👍
