### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by BenjaminHoegh** [ddeboer/imap#316]
When i add this code to my php file i get a http error 500
```
use Ddeboer\Imap\Server;

$server = new Server('imap.example.com');

// $connection is instance of \Ddeboer\Imap\Connection
$connection = $server->authenticate('my_username', 'my_password');
```

Why is this happning? Someting i miss?

**Comment by Slamdunk** [comment]
This library has nothing to do with HTTP, so I can't help you here

**Comment by BenjaminHoegh** [comment]
omg, I'm feeling stupid now. forgot to include the autoloader
