### ISSUE TITLE
Invalid argument supplied for foreach() in Parameters.php line 52

### ISSUE THREAD

**Issue by JosefRypacek** [ddeboer/imap#317]
Hi, I have another error - warning. Background is similar like in #310.

Function imap_mime_header_decode returns for one of my messages FALSE, so foreach will fail.

I've temporarily fixed this by modifiing MessageIterator.php
```
try {
set_error_handler(function($errno, $errstr, $errfile, $errline, array $errcontext) {
		if (0 === error_reporting()) {
			return false;
		}
		throw new \ErrorException($errstr, 0, $errno, $errfile, $errline);
	});
	$ret = new Message($this->resource, $current);
	restore_error_handler();
} catch (\Exception $e) {
	dump($e);
	\Tracy\Debugger::log($e->getMessage(), \Tracy\Debugger::ERROR);
	parent::next();
	return $this->current();
}
return $ret;
```

**Comment by Slamdunk** [comment]
Rather than you solution, we need your problem: can you post the original raw email that raised your error please?

**Comment by JosefRypacek** [comment]
I've modifed PII, removed 2 PDF attachments and replaced one included image. Hope it's ok.

[email.txt](https://github.com/ddeboer/imap/files/1810150/email.txt)

**Comment by Slamdunk** [comment]
Hi, I can't reproduce the error: may you post the full error message including the stack trace?

**Comment by JosefRypacek** [comment]
Hi, 
yes, you are right. Problem seems to be in attachment (I have been able to run the test).
Please see updated raw message.

[msg_fail.txt](https://github.com/ddeboer/imap/files/1821854/msg_fail.txt)

**Comment by Slamdunk** [comment]
Release in [1.4.0](https://github.com/ddeboer/imap/releases/tag/1.4.0)
