### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by billynoah** [ddeboer/imap#321]
Is there any more documentation or set of examples for this class?  How do I use the `Unseen` class?  Can you please explain more about how to search in greater detail?  Thanks

**Comment by JosefRypacek** [comment]
I'm not using this feature at the moment, but I would try following line. The rest of code can be found in readme.
`$search->addCondition(new Unseen());`

**Comment by Slamdunk** [comment]
`Mailbox::getMessages()` accepts as a first parameter any `Search\ConditionInterface`, so you can use `Search\Flag\Unseen` alone or as an or condition of `SearchExpression` because it implements the [Composite pattern](https://en.wikipedia.org/wiki/Composite_pattern)
