### ISSUE TITLE
Does the getMessages(); and associated foreach do a lazy-load? or a pre-load?

### ISSUE THREAD

**Issue by xmontero** [ddeboer/imap#326]
Hello,

I have an INBOX with about 150 normal-sized messages (some a few dozens of KB, some with a couple of MB).

It takes me about 40 seconds to display a simple page with the list of subjects, from, tos, ccs, etc.

Question: The loop in the README...

$messages = $mailbox->getMessages();

foreach ($messages as $message) {
    // $message is instance of \Ddeboer\Imap\Message
}

does this loop create a new connection to the IMAP server for each message? Does it download every message in full?

Or it downloads some kind of headers and only retrieves the full message in some kind of lazy-load when calling the ->getBodyHtml() or ->getBodyText() methods?

If it does a pre-download... what's the best approach to display an INBOX preview with full from+to[]+cc[]+bcc[] in addition to subject, date, etc. before getting the full content?

PD1: IDK if I can tag this as a question
PD2: After resolving I'll be happy to contribute to the repo explaining this in the README if that is allowed and helps anyone.

**Comment by Slamdunk** [comment]
Hi, you can take a look at https://github.com/ddeboer/imap/issues/286#issuecomment-358644987 for the answer.

But I'm trying to reduce the impact of that function call, stay tuned.

**Comment by Slamdunk** [comment]
A performance enhancement was just release on [1.5.0](https://github.com/ddeboer/imap/releases/tag/1.5.0), can you give it a try?

**Comment by xmontero** [comment]
Tried. Really made a difference.

Updated from "version": "1.2.3" to "version": "1.5.0" according to my `composer.lock` file.

I put some random 273 real messages in an `INBOX`.

* The "view inbox test page" in v1.2.3 lasted **61.120ms** (61+ seconds)
* The same page (no code change) just upgrading the library to v1.5.0 lasted only **7.521ms** (7+ seconds).

So there's a time-reduction of 87.6%.

Thanks. I think this issue can be closed at least for now.
