### ISSUE TITLE
Why the Server class is final? Why the methods private instead of protected?

### ISSUE THREAD

**Issue by xmontero** [ddeboer/imap#327]
I pass the Server in a symfony environment configured by a Dependency Injection system.

So... I have a custom ImapManager class that gets the Server class from the application config so my controllers depend on my model and not on the library (DDD approach, clean-code approach).

Instead, I want to "log" the accesses to the server and I want to log what hostname I am accessing (my deployer configures different server names to be "injected" for production and for testing/pre-production.

I then miss...
* either some public getters like `getHostname() : string` or `getPort() : int` in the Server,
* or either the class *not* being final *and* the properties protected so I could subclass the `Server` and implement the methods by myself.

Is there any reason for a client not being able to query how the server was created when the client did not create the server and therefore does not know the creation data?

If there's no reason for that, I'd be happy to contribute to the reason to improve it.

**Comment by Slamdunk** [comment]
Hi, you can find your answers in a similar issue recently closed: #318 

After reading it, if you still have questions ping me

**Comment by xmontero** [comment]
Okey, so the suggestion is then:

Instead of subclassing `Ddeboer\Imap\Server` just create a `MyProject\Server` class that creates a new `Ddeboer\Imap\Server` inside it and "proxies" it adding the functionality that you can need around.

Okey, I can buy this idea... This could avoid side-effects due to subclassing ensuring encapsulation. This could justify 50% of my question: Why the class is "final". Still, it could be under discussion if that's a decission that I have make or the creator of the library has to decide for me. In general I don't like others deciding for me, but, anyway, let's accept that.

There's the other 50% of my question then... if the class is made "final"... is there any sound reason for which there's not a public getHostname() that returns the construction parameter?

That would have a zero-side-effects in `Ddeboer\Imap\Server` (nobody consuming the getter can break anything) and has zero-impact in versioning (does not destroy backwards compatibility).

I can't clearly see any reason by which the class has to forbid me to know that information.

Assuming `final` is kept in place, is there any solid reason for forbidding the client to know what's the hostname to which we are connecting to?

If there's no reason for that, I'll be happy to contribute to the code.

**Comment by Slamdunk** [comment]
> If there's no reason for that, I'll be happy to contribute to the code.

And I'll be happy to review it :)

**Comment by Slamdunk** [comment]
Closed in https://github.com/ddeboer/imap/pull/333#issuecomment-444052168
