### ISSUE TITLE
Error running unit tests

### ISSUE THREAD

**Issue by xmontero** [ddeboer/imap#329]
I was about to contribute as per conversation #327 but I've got a problem:

First, I wanted to check the library passes the tests, so I don't break anything...

    ~$ cd /tmp
    /tmp$ git clone git@github.com:ddeboer/imap.git
    /tmp$ cd imap/
    /tmp/imap$ composer install
    /tmp/imap$ vendor/bin/phpunit

boom!!

![ddeboer_imap](https://user-images.githubusercontent.com/5641621/38034437-933250e4-32a2-11e8-995d-e6f82be172c7.png)

I switched to tag 1.5.0, just in case master is WIP...

    /tmp/imap$ git checkout 1.5.0
    /tmp/imap$ git reset --hard
    /tmp/imap$ rm -Rf vendor/
    /tmp/imap$ composer install
    /tmp/imap$ vendor/bin/phpunit

but got the same.

Shouldn't this just work? Or the tests are no longer maintained?

**Comment by Slamdunk** [comment]
Try to look at the doc: [Running the Tests](https://github.com/ddeboer/imap#running-the-tests)

**Comment by xmontero** [comment]
Well I guess that's for the **functional** test... for the **unit test** no external connections should be needed...

Maybe there's a subset of tests flagged as "functional" and another set flagged as "unit"?

**Comment by Slamdunk** [comment]
This library is a wrapper to raw PHP functions, which interact with an external services.
In such situation, 99% of the issues emerge with the external service itself, so 99% of the tests are functional ones.

By the way, if you are asking for implementing https://github.com/ddeboer/imap/issues/327, it should be easy to run only the new unit test you'll create, and then you can wait for Travis to tell you if anything brakes.

**Comment by xmontero** [comment]
Will do!
