### ISSUE TITLE
PHP Fatal error:  Uncaught ErrorException: [CLOSED] IMAP connection broken (server response)

### ISSUE THREAD

**Issue by santossoares** [ddeboer/imap#330]
Hi! i'm getting this error in the end of a long script file.
This is just a resume what it does:

1- download files from email using this library
2-processes the files
3-some other routines, etc

This error occurs in the end of my script.
I think this is because the connection is not closed after the download ends. So, when my script ends after 50mins, this error appears.
The script itself executes perfectly excepts it throws this error message in the end, preventing another script from running.

I'm using the 1.2 version of the library.
In another server i was using the version 0.5 and it worked perfectly.

**Comment by Slamdunk** [comment]
Hi, there should be another part in the error message, may you post it please?

**Comment by santossoares** [comment]
Hi! this is the error message:
I'm using laravel 5.5. The scripts are artisan console commands.

PHP Fatal error:  Uncaught ErrorException: Unknown: [CLOSED] IMAP connection broken (server response) (errflg=1) in Unknown:0
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Unknown: [CLOSE...', 'Unknown', 0, NULL)
#1 {main}
  thrown in Unknown on line 0
Segmentation fault (core dumped)

**Comment by Slamdunk** [comment]
Hy, have you tried using `$connection->close()` at the end of the script?

**Comment by santossoares** [comment]
@Slamdunk Hi, i tested using $connection->close() at the end, and the error disappears! Thanks for your time!
