### ISSUE TITLE
Cannot mock EmailAddress

### ISSUE THREAD

**Issue by xmontero** [ddeboer/imap#331]
I have a class that uses the Message class to get it's From address. I'm unit-testing my class. I need therefore to mock the class Message, so it returns me a certain "From".

Instead, when mocking, phpunit says that it is not mockable since it is "final".

There are several comments around in this repo that say that mockability is guaranteed via interfaces, but this is not exactly true. Let me give an example:

* Message implements MessageInterface.
* MessageInterface extends Message\BasicMessageInterface
* Message\BasicMessageInterface does have a getFrom() which returns an EmailAddress.
* Nevertheless EmailAddress is not an interface, it is a class.
* In addition it is final.
* In addition this class does not implement any interface.

The last 3 together result in that EmailAddress cannot be mocked.

This means I cannot ask phpunit to mock a MessageInterface to return me a certain EmailAddress.

I'd suggest one of the following strategies:

1. Either make interfaces ONLY depend on interfaces.

2. Either convert all the classes that are not services, into value objects (certainly an EmailAddress class *is* to all effects a Value Objects) so we can make them immutable. If we make them immutable we may remove the "final" keyword as it is impossible to have side effects (unless the coder effectively wants to trick it, which is for example the case of mocking where we want to fake the real behaviour).

QUESTION:
Alternatively... In the meanwhile... What's the best way to have PhpUnit return me a mocked EmailAddress from a mocked Message?

PD: I was going to place a comment here towards a new more-clean DDD+TDD oriented API, but I think I should open a new issue for that as it is independent.

**Comment by Slamdunk** [comment]
EmailAddress already is a Value Object, it already is immutable.

Value Objects don't have a behaviour, and can't change. Value Objects are exactly like an array, an immutable array. You should use them directly in the tests.

You shouldn't mock value objects, why should you do that?

**Comment by xmontero** [comment]
There are some Value Objects that are huge and complex to construct.

Let's say for example you may have an invoice that contains a set of data for example: who is issuing the invoice, who is the destination, the content (array of invoice lines), each being sub-objects that also are value-objects that are part of the value itself.

If you have a test of a service that deals with invoice dates, you may want to have a "fake invoice" that only responds the date, and you do not "need" to worry about "creating a fully-compliant set of data for the constructor".

In my tour-operator (I sell trips) for example a "quotation" is a value object. Each quotation is "the one and only one", and is immutable and it depends uniquely on its value. And it is a very-huge value object that contains things like "what flight responses gave the flights API and at what UTC time-stamp we checked the flight prices" or "the full array of days, and per each day, the full array of activities, and for each activity the id of the tariff document we used to calculate this quotation". And the activities, in turn, contain the "pick-up time" and the "return time" that was "stated by the provider" at the moment of the quotation.

And all that is a single Value Object. Complex, but only one.

And that contains creation rules, like for example: You cannot have an itinerary that has activities that overlap in time. If you have activity A ending at 5pm and activity B starting at 4pm, this yields in an Exception at creating the value object.

Of course when I need to test services that need a quotation (for example a service that saves the last 100 quotations to somewhere), of course in the test of the service I don't need to create 100 "real" quotations with all that work. I just create 100 mocks. And if the service needs something like the timestamp of the creation of the quotation, I'll make the mock just respond to that method.

So, in general terms, I think that there's no need to restrict by code to the one consuming the classes if the value objects are mockable or not. In favour or unit-testing, all classes should be mockable. You cannot determine the scenarios in which the consumers will need to use them.

In this particular case, to mock a `getAddress()` and get `alice@example.com` one should not need to replicate the counter-logic of the constructor building that each time it needs it.

On the other side.... emm.... even if I could accept that... "okey, that's a rather simple value object, let's build it"... There's a code smell: Interfeces should *only* depend on interrfaces.

There's no constructor overload in PHP, so if you have an interface `CalculatorInterface` that may deal with complex numbers `Complex` that you create by giving the real and the imaginary part... and the `CalculatorInterface` has a method that depends on the concrete (final!?) class instead of a `ComplexInterface` class, then you, as a consumer, if you ever need to construct `Complex` numbers by constructing them by a modulus and an angle, you will not be able to "inject" them into the calculator service.

So I completely agree that inside a company, a CTO might set the rule "hey guys, all classes final" so the team does not go wild and if we ever get blocked it is that we need to talk". And a CTO might also say "hey those specific interfaces may depend on those specific classes".

I agree that when you are doing an application, that could state true. Instead, when you are doing a library for third parties, I think that the criteria should be biased towards the oposite:

a) All interfaces depend only on interfaces, so the consumer will inject whatever he wants there provided that the methods are there.
b) The classes should not be final, except, perhaps, maybe, the only one that touches the real world, to avoid side effects.

While I agree that your criteria is beneficial in some specific cases, I would suggest to talk more deeply when it is for a public library in which the coder of the library should not "restrict" the coder of the consuming application other than sticking to the methods in the public API.

I think that more than an "EmailAdress" issue, there is an evolving philosophical dialog here... I don't know if there's any point on discussing it here in github but in the commits of my pull request you have my email address there. I'd be glad to meet privately, maybe over skype, and chat about all that.

I'm a super fan of clean code, I selected this imap library over barbushin's one because of the code cleanness, and I'd love to see this library to become more and more used by everyone.

As always, this is not a black/white thing and maybe I'm missing any gray that you are seing and that for any reason I'm unable to see now.

I'd love to hear more on that.

**Comment by Slamdunk** [comment]
> And all that is a single Value Object. Complex, but only one.
> 
> And that contains creation rules

A Value Object never has rules nor logics, otherwise is not a VO anymore.

> a) All interfaces depend only on interfaces

I disagree: interfaces are allowed to depend upon VOs.

Interfaces shall not depend upon implementations, and a VO is not an implementation because doesn't have logics.

> b) The classes should not be final, except, perhaps, maybe, the only one that touches the real world, to avoid side effects.

As long as an OOP architecture respects all the [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) principles, it can be whatever it want.

As far as I can see, the current `final` keyword usages don't violate any of the SOLID principles.


I would be happy to read some documentation that disprove any of the above statement.
