### ISSUE TITLE
Towards v2.0.0

### ISSUE THREAD

**Issue by xmontero** [ddeboer/imap#332]
I was about to place a comment in issue #331 but it was growing too much, so I decided to place a second issue as this is a different story.

The issue #331, together with other several issues, make me think in start working towards a proposal for a v2.0.0

This could maintain all the functionality but change the public interface so it is better architecturized and more DDD+TDD oriented: use immutable value objects when possible, make all the classes unit-testable (independently of the fact that there are already functional tests in place, and they are okey too), and several more.

In issue #329 it seems that the focus is on the functional tests, and the comments from @Slamdunk suggest me that there is a bit of overlap between two **different** responsabilities that this library has:

* First, as per @Slamdunk comment, (textual cite) "This library is a wrapper to raw PHP functions"
* Second, futhermore, this library gives a good set of logic and structure and approaches the access to the IMAP as structured objects.

I think then, that the architecture should be in two layers:

a) The low-level: An ImapBridge class that just has every method that we'll call in the low level.
b) The high-level: Objects that represent the "Domain" (Server, Mailbox, Message, Part...)

This way we can completely decouple the logic of one with respect from the other. In fact in the limit, they could be two different separated repositories.

In the high level we should completely avoid any use of the "null" keyword. For example, the `getFrom()` of the message which now returns `null | EmailAddress` and therefore one consumes it like this:

    $from = $message->getFrom();
    if( ! is_null( $from ) )
    {
        doSuccessWork();
    }
    else
    {
        doFailureJob();
    }

should be like this:

    if( $message->hasFrom() )
    {
        $from = $message->getFrom();
        doSuccessWork();
    }
    else
    {
        doFailureJob();
    }

This allows us to inforce return types, provided we are restricting this library to PHP 7.0+ according to the documentation, and have this signature, for example:

    public function getFrom() : EmailAddress

This will ensure that always that we call getFrom, we get a valid object.

This general architecture approach, separating what is low-level from what it should be ultra-clean, pure-(DDD+TDD)-oriented, high-level code will enable two things:

a) No need to "protect" the high level classes with the "final" keywords. The coders will be free to choose what to do with them. This removes a constraint while guaranteeing all the security and therefore will promote more users to adopt this library as their main one.

b) We will just "inject" the low-level class into the high-level one. This allows us to mock all the unit-tests without the need of any functional test.

We can in addition take advantage of the compatibility break to upgrade some weird things. For example, the Server has a port parameter in the constructor and I see it accepts a string... Unless there's something I'm missing, TCP-IP ports have been always numbers... and if there's any "conversion" from string to number it is "not" responsability of the Server if we want attain the "responsability segregation" principle.

I'd be happy to contribute to the architecture design, if needed.

**Comment by Slamdunk** [comment]
> a) The low-level: An ImapBridge class that just has every method that we'll call in the low level.
> b) The high-level: Objects that represent the "Domain" (Server, Mailbox, Message, Part...)
> 
> This way we can completely decouple the logic of one with respect from the other. In fact in the limit, they could be two different separated repositories.

I understand this point.
But I'm still against because in the experience I matured developing code with imap extension, almost all the issues came from the extension itself, and almost zero from the domain logic of this library.

Once you take into account this point, you can understand that the added maintainability burden doesn't compensate the added value.

> ```php
> if( $message->hasFrom() )
> {
>     $from = $message->getFrom();
>     doSuccessWork();
> }
> ```

This would be a good improvement, and I would consider positively a PR in such way

> a) No need to "protect" the high level classes with the "final" keywords. The coders will be free to choose what to do with them. This removes a constraint while guaranteeing all the security and therefore will promote more users to adopt this library as their main one.

I don't get how an API change like the above removes the necessity of final keyword.
Coders are already free to choose what to do with them, aren't they?
