### ISSUE TITLE
Undeliverable mail: attachment parsing error

### ISSUE THREAD

**Issue by bastian-schur** [ddeboer/imap#334]
Hi,

i've parsed a undeliverable mail with the original mail as attachment. When i use the getAttachments function from Message i get the attachments from the original mail ( attached as .eml file ) and not the correct attachments for this mail. The content of the attachments is always null!

**Comment by Slamdunk** [comment]
Hi, we need:

1. the original mail content retrieved with the `$message->getRawMessage()`
1. the calls that you do to this library
1. what you expect exactly

**Comment by Slamdunk** [comment]
I'm sorry but without the original email we can't reproduce the bug.

Maybe you can:

1. Send the email to my personal email, I'll dig into the bug and drop the sensitive content
1. Post here the email with the sensitive content stripped out

**Comment by bastian-schur** [comment]
Hi,
i've generated a test mail with the same problem:
The Base E-Mail has an attachment named

**Comment by bastian-schur** [comment]
I try to generate a testmail an give you more feedback!
