### ISSUE TITLE
$mailbox->getAttributes() not found

### ISSUE THREAD

**Issue by AndriusCTR** [ddeboer/imap#335]
Hi,

Using your example code (from main page), I get error that method not found. How to exclude containter-only mailboxes then?

```
    if ($mailbox->getAttributes() & \LATT_NOSELECT) {
        continue;
    }
```

Thanks

**Comment by Slamdunk** [comment]
The method is present till version 1.0, be sure you are using the latest version available (as today is 1.5):

https://github.com/ddeboer/imap/blob/888139dd42b0b0ed06493168365ea3b1f762abdc/src/Mailbox.php#L78-L86
