### ISSUE TITLE
Difficult display 'date' of getDate()

### ISSUE THREAD

**Issue by halojoy** [ddeboer/imap#339]
First let me say I like this IMAP very much.
And I have now tried several other applications.
```php
$datum = $message->getDate();
print_r($datum);
```
gives:
DateTimeImmutable Object
(
    [date] => 2018-04-15 09:36:36.000000
    [timezone_type] => 1
    [timezone] => +00:00
)
Now if I try the expected:
```php
echo $datum->date;
```
then I get this error:
Undefined property: DateTimeImmutable::$date in C:\Apache24\htdocs\ddeboerimap\

I wonder why? I have tried to get the 'date' to display.
But nothing helps.

**Comment by Slamdunk** [comment]
DateTimeImmutable is part of native PHP standard library, please refer to the manual for how to interact with it: https://secure.php.net/manual/en/class.datetimeimmutable.php
