### ISSUE TITLE
In getMessages() how to set the 'search' parameter?

### ISSUE THREAD

**Issue by halojoy** [ddeboer/imap#340]
getMessages(**$search**, $sortCriteria, $descending)
I have tried:
$messages = $mailbox->getMessages('SINCE "2017-07-01"', SORTDATE, true);
But I only get an error for the 'search' part.
_Argument 1 passed to Ddeboer\Imap\Mailbox::getMessages() must be an instance of Ddeboer\Imap\Search\ConditionInterface or null_

**Comment by Slamdunk** [comment]
As said by the error, you must provide an instance of `Ddeboer\Imap\Search\ConditionInterface`, not a string.

The exact code yu are looking for is reported in the readme: https://github.com/ddeboer/imap#searching-for-messages
