### ISSUE TITLE
Delete Message 

### ISSUE THREAD

**Issue by Mahdi-Ba** [ddeboer/imap#345]
I`m running below code for delete message. Then  remove from inbox and hide from there  
```
foreach ($messages as $message) {
 $message->delete();
}
```
But after remove Call again get Message same as remove message and I`m forcing do this  
```
if ($message->isDeleted()) {
continue;
 }
```

**Comment by Slamdunk** [comment]
As written in the readme https://github.com/ddeboer/imap#message-properties-and-operations you need to expunge the connection in order to actually delete them.
