### ISSUE TITLE
Copy mail between accounts

### ISSUE THREAD

**Issue by hexblot** [ddeboer/imap#346]
Assuming two different server connections exist (instances of `\Ddeboer\Imap\Server`): 

- `$source` and 
- `$target`

with two respective mailboxes  ( instances of `\Ddeboer\Imap\Mailbox`):

- `$sourcemail` from  `$source` and 
- `$targetmail` from `$target` 

what would the proper procedure be in order to copy an email from `$sourcemail` to `$targetmail`?

Is it possible, for a given message in `$sourcemail` to use `$message->getRawMessage()` and then add that raw email to `$targetmail->addMessage()`? Does that cover attachments/properties (read, time created, etc)?

Thank you in advance!

**Comment by Slamdunk** [comment]
> Is it possible, for a given message in $sourcemail to use $message->getRawMessage() and then add that raw email to $targetmail->addMessage()?

Yes it should work like this.

> Does that cover attachments/properties

Attachments yes, Properties I think not.

**Comment by hexblot** [comment]
Thanks for the über-prompt response, writing the code now and will revert.

**Comment by Slamdunk** [comment]
Note that `addMessage` method let you specify some flags and the time the IMAP server will mark the message in the Mailbox:

https://github.com/ddeboer/imap/blob/7e3a31dfd92f0dfd24af03dff63b25eba2d1a805/src/Mailbox.php#L203-L213
