### ISSUE TITLE
How can I get back only a certain number of mail?

### ISSUE THREAD

**Issue by Marlight** [ddeboer/imap#347]
For a synchronization, I am only allowed to read out a certain number of emails. The reason for this is that the PHP RAM is not big enough to sync a mailbox at once. How can I always have 100 emails returned, for example?

**Comment by Slamdunk** [comment]
Maybe you can count the already retrieved messages, save the ID of the last retrieved one, and if 100 is reached you stop the run, and the successive run will start from the last ID retrieved.

**Comment by uomopalese** [comment]
Maybe this can help someone else.
```
$i = 1;
foreach ($messages as $message) {
  // do your stuff
  //...
  if ($i++ === 100) break;
}
```
