### ISSUE TITLE
Search by date does not works

### ISSUE THREAD

**Issue by zstergios** [ddeboer/imap#349]
On give example on readme page.

( ! ) Fatal error: Uncaught Error: Class 'Ddeboer\Imap\Search\Date\Since' not found in F:\wampserver\www\serverlogs\index.php on line 35

**Comment by Slamdunk** [comment]
Well, like every PHP class used inside another namespace, you have to import it with a use statement: https://secure.php.net/manual/en/language.namespaces.importing.php

The class exists: https://github.com/ddeboer/imap/blob/master/src/Search/Date/Since.php
