### ISSUE TITLE
setFlag / markAsSeen not found

### ISSUE THREAD

**Issue by zstergios** [ddeboer/imap#350]
I have searched in all project's folder, both functions does not exists.
Am I missing something? (Version 1.5.1)
http://prntscr.com/jnza01

**Comment by Slamdunk** [comment]
Hi, I don't know how you serach them, but you can browse them here in github and you find both:

https://github.com/ddeboer/imap/blob/7e3a31dfd92f0dfd24af03dff63b25eba2d1a805/src/Message.php#L253-L261

https://github.com/ddeboer/imap/blob/7e3a31dfd92f0dfd24af03dff63b25eba2d1a805/src/Message.php#L312-L326

**Comment by zstergios** [comment]
I found the reason.
On my system was declared PHP v 5.6, so I thought that I had installed the 1.5.1 version but I had 0.5.2
I suggest you to remove the older version.

I changed the system variable php to point on PHP7.
