### ISSUE TITLE
Date + conditions

### ISSUE THREAD

**Issue by zstergios** [ddeboer/imap#351]
Hi, there is any way to pass both objects to getMessages?

$search = new SearchExpression();
$search->addCondition(new From('@test.com));

$today = new DateTimeImmutable();
$lastMonth = $today->sub(new DateInterval('P1D'));
$search1=new Ddeboer\Imap\Search\Date\Since($lastMonth);

Probably would be better to change function
public function getMessages(ConditionInterface $search = null,
to
public function getMessages($search = null,

        if (null === $search) {
            $search = new All();
        }

        $query =is_object($search)? $search->toString():$search;

I found that someone requested to mege the mailbox.php. I tested and seems works nicely.
getMessagesPagination function is very usefull.

Also think about to prevent the code douplication on getMessages and getMessagesPagination

**Comment by Slamdunk** [comment]
If you want to pass multiple search condition, use the SearchExpression like itis written in the readme: https://github.com/ddeboer/imap#searching-for-messages

```php
$search = new SearchExpression();

$search->addCondition(new From('@test.com'));

$today = new DateTimeImmutable();
$lastMonth = $today->sub(new DateInterval('P1D'));

$search->addCondition(new Since($lastMonth));

$messages = $mailbox->getMessages($search);
```

> public function getMessages($search = null,

How would this be better? Enforcing objects usage makes the library much more reliable and future-proof.

> I found that someone requested to mege the mailbox.php. I tested and seems works nicely.
> getMessagesPagination function is very usefull.
> 
> Also think about to prevent the code douplication on getMessages and getMessagesPagination

What are you referring to?

**Comment by zstergios** [comment]
Thank you!!!!!
>>What are you referring to?
https://github.com/ddeboer/imap/pull/307/files

https://github.com/morpheus747/imap/blob/96c7ce6eaf5bdf04ebae49d1a8aa3677a78240b1/src/Mailbox.php#L150

**Comment by Slamdunk** [comment]
DateTimeImmutable is immutable, modify method doesn't alter it, it only return a new object that you are discarding.
May you try with a valid date in the past please?
