### ISSUE TITLE
last folder in list

### ISSUE THREAD

**Issue by theblizzle** [ddeboer/imap#353]
im using your library(sorry first time ever posting an issue) but the last folder when you loop to show folders the last folder when u do the $imap->getMailbox() it loads the inbox folder. if you make a new folder the folder before that will start working even specifying a folder (ie Spam) if spam was the last folder it would load the folder inbox.  even in my logs for hmailserver say its grabbing the inbox when i tell it the last folder any help would be appreciated im running latest build

**Comment by Slamdunk** [comment]
Hi, may you share the folder structure of your mail server, and a code snippet that reproduce the issue?
