### ISSUE TITLE
Fails to load Message Headers

### ISSUE THREAD

**Issue by addiks** [ddeboer/imap#358]
When I try to download E-Mail's from an IMAP account, i get the following error message:
`Type error: Argument 1 passed to Ddeboer\Imap\Message\Headers::__construct() must be an instance of stdClass, boolean given`

This error happens on the first message it tries to download, which hints to it being a systematic issue rather then a broken message.

After a bit of debugging i found out that the issue is that "imap_headerinfo" returns false in [Message.php at line 154](https://github.com/ddeboer/imap/blob/7e3a31dfd92f0dfd24af03dff63b25eba2d1a805/src/Message.php#L154).

![bildschirmfoto vom 2018-07-04 17-45-47](https://user-images.githubusercontent.com/3450330/42285716-b0fff27e-7fb0-11e8-81f6-12faef22a1ce.png)

I do not know yet why this call to imap_headerinfo fails, but at least a bit of error-handling should be added at this point to catch this error and display a nicer message.

Maybe i will write a PR for this, but first i will try to figure out **why** this call fails.

**Comment by addiks** [comment]
Looks like the call to imap_headerinfo fails because it was trying to fetch the header-info's for a "message" that was not really a message, but a contact in a public folder.

I had set my program to just iterate over all "mailboxes" to collect all mail's. The first "mailbox" it encountered was a public folder full of contacts.

When i just download the messages from the INBOX folder, everything works as expected.

Maybe there should be some better error-handling for this case. Is there a way to check beforehand if a message is actually a contact and not a message? Or if a folder does not contain messages but contacts?

**Comment by Slamdunk** [comment]
Hi, thank you for this report.

> Maybe there should be some better error-handling for this case.

For sure there should be, we just didn't even imaged this case

> Is there a way to check beforehand if a message is actually a contact and not a message? Or if a folder does not contain messages but contacts?

No, as we didn't know there could be contacts retrieved as messages.

We need some details to reproduce the issue and (we hope to) create a test on our Dovecot test suite, can you give us:

* the IMAP provider (GMail?)
* the folder structure
* the return value of `$message->getRawMessage()`; you may strip sensitive data but please retain the format of that data, so instead of deleting your friend name, replace it with *John Doe* etc.

**Comment by addiks** [comment]
We host our e-mails on our own kopano instance.
The folder with the contacts is "Public folders/GAB".
The headers of the first message is:

`
Subject: John Doe
From: invalid@invalid
To: undisclosed-recipients:;
Date: Tue, 27 Feb 2018 09:33:15 +0000
Mime-Version: 1.0
Content-Type: application/ms-tnef; name=winmail.dat
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=winmail.dat
`

Also there was an base64-attachment which i did not decode because i don't have the time at the moment.

**Comment by Slamdunk** [comment]
Hi, I wasn't able to reproduce the bug because Dovecot returns all the headers you mention, even when the "email" is completely empty.

May you checkout my branch https://github.com/Slamdunk/imap/tree/false_imap_headerinfo and test that the error is now manageable?

**Comment by addiks** [comment]
This works for me.

Now that an appropriate exception is thrown for this case, i can catch it, ignore that "message" with it's invalid headers and carry on. Thanks!

**Comment by Slamdunk** [comment]
Fix released in [1.5.2](https://github.com/ddeboer/imap/releases/tag/1.5.2)
