### ISSUE TITLE
How to find charset or convert body

### ISSUE THREAD

**Issue by KodaCCH** [ddeboer/imap#362]
Hi

I will read all Mails with this class and insert the complete body to sql database.
```php
if (!empty($message->getBodyHtml())) {
    $messageBody = $message->getBodyHtml();
} elseif (empty($message->getBodyHtml()) && !empty($message->getBodyText())) {
     $messageBody = $message->getBodyText();
} else $messageBody = 'no body';
```

This works. But when i will forward the body with php mail, one mail work, another has utf8 charset problems and other I get an error like "DOMDocument::saveHTML(): output conversion failed due to conv error, bytes 0xFC 0x67 0x74 0x20"

How can I convert all content in utf8 to save in database?

**Comment by Slamdunk** [comment]
Hi, the issue you get is strictly related to the email content and not to this library.

If you prefer to take more controler over the email contents, you can use `$message->getRawMessage()` to gather the original content of the email and then parse it manually.
