### ISSUE TITLE
Content-Transfer-Encoding: 8bits  Undefined offset: 6  Error: Cannot decode 

### ISSUE THREAD

**Issue by kolorafa** [ddeboer/imap#364]
This is an older version of code, and this looks more like a PHP bug rather than code, but maybe there is some workaround for that (other than my probably bad one)?

```
2018-08-16 12:11:36 Notice: Undefined offset: 6 in [/var/www/clients/client88/web937/web/plugins/ImapConnector/Vendor/ddeboer/imap/src/Message/Part.php, line 221]
Error: Cannot decode 
#0 /var/www/clients/client88/web937/web/plugins/ImapConnector/Vendor/ddeboer/imap/src/Message.php(221): Ddeboer\Imap\Message\Part->getDecodedContent(false)
#1 /var/www/clients/client88/web937/web/plugins/ImapConnector/Console/Command/ImapConnectorShell.php(158): Ddeboer\Imap\Message->getBodyText()
```

Afected lines:
line 221: $this->encoding = $this->encodingsMap[$structure->encoding];
$structure->encoding is set to 6, but the valid values from imap_fetchstructure are from 0 to 5, but it somehow returns 6 while fetching from gmail...

I did put a hack to rewrite 6 into 1, but that might be bad in long term.
Email content that triggered this bug:
https://pastebin.com/wC74yznv

**Comment by Slamdunk** [comment]
Hi, this bug is present only in an old version of this library.

Only the latest version is supported, so please upgrade it.
