### ISSUE TITLE
Very long filename, result of getFilename() = NULL?

### ISSUE THREAD

**Issue by Marlight** [ddeboer/imap#365]
I have received a mail with a looooong filename... (Why peope do this?!? But is it reality..) The problem is, the Filename is "NULL"?

> Content-Type: application/pdf;
>  name\*0\*=utf-8''Buchungsbest%C3%A4tigung-%20Rechnung-Gesch%C3%A4ftsbedingung;
>  name\*1\*=en-Nr.B123-45%20-%20XXXX%20xxxxxxxxxxxxxxxxx%20XxxX%2C%20L%C3%BCd;
>  name\*2\*=xxxxxxxx%20-%20VM%20Klaus%20XXXXXX%20-%20xxxxxxxx.pdf
> Content-Disposition: attachment; size=70551;
>  filename\*0\*=utf-8''Buchungsbest%C3%A4tigung-%20Rechnung-Gesch%C3%A4ftsbedin;
>  filename\*1\*=gungen-Nr.B123-45%20-%20XXXXX%20xxxxxxxxxxxxxxxxx%20XxxX%2C;
>  filename\*2\*=%20L%C3%BCxxxxxxxxxx%20-%20VM%20Klaus%20XXXXXX%20-%20xxxxxxxx.p;
>  filename\*3\*=df
> Content-Transfer-Encoding: base64

`$attachment->getFilename() => NULL`
How can i fix this?

**Comment by Slamdunk** [comment]
It is a bug indeed, but I think related to the extension itself (reproduced in #366).

I'll analyse it in the next weeks.

**Comment by Slamdunk** [comment]
Bugfix released in [1.5.4](https://github.com/ddeboer/imap/releases/tag/1.5.4)
