### ISSUE TITLE
Move charset conversion to separate library?

### ISSUE THREAD

**Issue by zbateson** [ddeboer/imap#369]
Hello,

I noticed this library is maintaining a very similar set of functionality I'm using for charset conversion, and (it seems if I'm not mistaken) you previously had it separated out into ddeboer/transcoder, but have since moved it back in?

Any interest in moving that back out?  It seems we're duplicating our efforts, and we may both benefit from having that separated.  One of my users just reported '134' as a charset, which you came across and your solution and link in #270 helped me fix it.

My current implementation is here: [zbateson/StreamDecorators - CharsetConverter.php](https://github.com/zbateson/StreamDecorators/blob/master/src/Util/CharsetConverter.php) -- in a library currently only used by [zbateson/MailMimeParser](https://github.com/zbateson/MailMimeParser) so far as I know.  Anyway, it doesn't necessarily belong under there and I would be happy to separate it out ([ddeboer/transcoder](https://github.com/ddeboer/transcoder) or wherever, no matter).

My implementation differs a bit from yours:

- uses mb_list_encodings to find if charsets are supported first... strips out non-alphanumeric chars, and searches case-insensitively, in addition to maintaining a list of aliases
- failing that falls back to iconv with its own list of aliased charsets
- caches results in case they're reused
- I needed a few other multibyte functions besides convert: getLength and getSubstr
- I also need to support php 5.4 still as I'm supporting some older RH6 linux machines that run 5.4.

I unfortunately didn't keep a reference to where I originally found the aliases and mine are not as well organized as yours as well.  There are probably aliases we're both still missing if we merged our efforts.

It seems to me ddeboer/transcoder could be modified to include a merged list of our aliases, plus the additional functionality I've implemented as well without too much difficulty :)

**Comment by Slamdunk** [comment]
> Any interest in moving that back out?

No sorry: email parsing is a nightmare by itself, encoding is a nightmare by itself, and email parsing + encoding is just hell. Our implementation is strictly coupled with the purpose of this library and the real examples we gather from real emails.
Having a separate library only generated issues for us.

> * uses mb_list_encodings to find if charsets are supported first... strips out non-alphanumeric chars, and searches case-insensitively, in addition to maintaining a list of aliases
> * failing that falls back to iconv with its own list of aliased charsets

My experience tells me `MB-String` is nicer, but `iconv` is more reliable. This is why in this library now `iconv` comes first and I would like to notice you to pay attention too. I don't have scientific reasons for that, only my experience.

> mine are not as well organized as yours as well

We have a specific test to check loop references, I suggest you to implement something similar:

https://github.com/ddeboer/imap/blob/acf56f54375babb27a245338a13f4e8246975268/tests/MessageTest.php#L125

> It seems to me ddeboer/transcoder could be modified to include a merged list of our aliases, plus the additional functionality I've implemented as well without too much difficulty :)

I really appreciate your purposeful spirit and thank you for your try, but I don't feel this could improve this very library.

By the way, all this code is released under [MIT license](https://github.com/ddeboer/imap/blob/master/LICENSE), so feel free to copy-paste everything you need.

**Comment by zbateson** [comment]
Understand, no problems at all.

> By the way, all this code is released under MIT license, so feel free to copy-paste everything you need.

Thank you.  I was mostly hoping to avoid that approach, but I'll most likely scrape yours to check for any I missed.

> We have a specific test to check loop references, I suggest you to implement something similar:

Very good idea also, thanks for the suggestion!

All the best, feel free to close this or keep open for others thinking of something similar, as you like.
