### ISSUE TITLE
getFrom(), getTo and getSender() result empty

### ISSUE THREAD

**Issue by martin-schaap** [ddeboer/imap#370]
Hi,
Trying to get message properties from messages:
```php
$from = $message->getFrom();    // Message\EmailAddress
$sender = $message->getSender();
$to = $message->getTo(); 
$headers = $message->getHeaders();
```
All give empty result, but others like getSubject(), getDate() do give result as expected. What do I do wrong here?

Thanks,
Martin

**Comment by Slamdunk** [comment]
Hi, can you post the raw message that originated the issue you describe?

**Comment by martin-schaap** [comment]
This is the piece of code used:
		sc_include_library("prj", "ImapLib", "vendor/autoload.php", true, true);
		$server = new Ddeboer \ Imap \ Server(
			$hostname, // required
			$port,     // defaults to '993'
			$flags    // defaults to '/imap/ssl/validate-cert'
		);
		$connection = $server->authenticate($username, $passwd);
		$mailboxes = $connection->getMailboxes();

		foreach ($mailboxes as $mailbox) {	
			$messages = $mailbox->getMessages();
			foreach ($messages as $message) {

				$msg_subject			= $message->getSubject();
				$msg_from				= $message->getFrom();    // Message\EmailAddress
				$msg_sender				= $message->getSender();
				$msg_to					= $message->getTo(); 
				$msg_headers 			= $message->getRawHeaders();
				echo '<br /> -----------------------------------------------------------------';
				echo '<br />msg_subject: ' 	. $msg_subject;
				echo '<br />msg_to: ' 		. $msg_to[0];
				echo '<br />msg_sender: '	. $msg_sender[0];
				echo '<br />msg_from: ' 	. $msg_from;
			}
		}
I cannot use 'use Ddeboer\Imap\Server;' because it runs from a Scriptcase function. For that reason I used '$server = new Ddeboer \ Imap \ Server()'.

Result:
-----------------------------------------------------------------
msg_subject: tezZie
msg_to: 
msg_sender: 
msg_from: 

So it retrieves the subject, but not the other values.

Thanks

**Comment by martin-schaap** [comment]
Here it is:

Return-Path: Received: from deliver ([unix socket]) (authenticated user=livetoseeafr07 bits=0) by server12.firstfind.nl (Cyrus 2.5.10-Debian-2.5.10-3) with LMTPA; Sun, 30 Sep 2018 23:18:28 +0200 X-Sieve: CMU Sieve 2.4 X-Spam-Checker-Version: SpamAssassin 3.3.2 X-Spam-Level: X-Spam-Status: No, hits=0.0 required=5.0 tests=HTML_MESSAGE,MIME_HTML_MOSTLY, SPF_PASS,TVD_SPACE_RATIO autolearn=unavailable version=3.3.2 X-Original-To: travel2@livetoseeafrica.com Delivered-To: livetoseeafr07@server12.firstfind.nl X-Virus-Scanned: by amavisd-new-2.7.1 (20120429) (Debian) at firstfind.nl Received: from filter04.hostcontrol.com (filter04.hostcontrol.com [5.157.86.29]) by server12.firstfind.nl (Postfix) with ESMTPS id 386ECE84289 for ; Sun, 30 Sep 2018 23:18:22 +0200 (CEST) Received: from d103165.upc-d.chello.nl ([213.46.103.165] helo=Win7Parallels) by filter04.hostcontrol.com with esmtpsa (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256) (Exim 4.89) (envelope-from ) id 1g6j6a-0007Pp-Mk for travel2@livetoseeafrica.com; Sun, 30 Sep 2018 23:18:21 +0200 Reply-To: From: "Martin Schaap" To: Subject: tezZie Date: Sun, 30 Sep 2018 23:18:20 +0200 Message-ID: <002201d45903$1d2428f0$576c7ad0$@turtle-productions.nl> MIME-Version: 1.0 Content-Type: multipart/alternative; boundary="----=_NextPart_000_0023_01D45913.E0ACF8F0" X-Mailer: Microsoft Outlook 16.0 Thread-Index: AdRZAxylyYtCc/XFQ/6RBzIoloZmvg== Content-Language: nl X-Originating-IP: 213.46.103.165 X-Hostcontrol-Domain: turtle-productions.nl X-Hostcontrol-Username: turtleproduc01 Authentication-Results: hostcontrol.com; auth=pass (login) smtp.auth=turtleproduc01@turtle-productions.nl X-Hostcontrol-Outgoing-Class: unsure X-Hostcontrol-Outgoing-Evidence: Combined (0.50) X-Recommended-Action: accept X-Filter-ID: EX5BVjFpneJeBchSMxfU5k2Ige/jFLezdYC8jMAFgN5602E9L7XzfQH6nu9C/Fh9KJzpNe6xgvOx q3u0UDjvO92Py4FMkMeydWMEUJPu4mcHX0uzgVTYnca6CDN1l8Gu1kN9h/JMaXpH3QAmrQScTWLr 82UcHyyxaoey+OgnmC6nH/uMuybLqnATUjKobC5e3lRz6+lgDS61THPnK4cxtUtj7naDy7N0Bswc VVayGrLxIccAphzxuiUQSqYVXVw5/crUMSB3/ZTeY4yyWjyvJTaCBgq9o3jPb74nfE4uqzrF119D VHRNEI2TGS+UM/EQ2dZGspqhQh0aervpiISF4DsPJhlJuEwx3s5CRunG2FcIgkaUWfVCRTRNiTpw ymJWvGgR0QuUtWrZYJVqrzSE7WPZkpdo7hk5KPYqWGvwiC+NDgfBsXhpZpGXRrEDnbmi5YE5enyc cp7RH4WQio3uGQCkjSSYNTpjQQaMIB+jJTFawstRTdMAa0q1mRuFuaH1xRamOeYDBIwBrxIWz+W8 eik4xAm9D8KTeKJT7gNACPfTsx3KBtgDA/3kdj1M8cyt42VXg9ug3PiipBW7g+muvBprxtFAUO1+ 9aG3qi0SJ786B4CF7QBQ/oqmYf3Z/d6VhJKO0HXjIOPGlWOKWte4nF4WT/2UqKy3bQ4/FBMRLPDk x3zXTOEkFeqx8+aPEYxJ92PNDpgLsd6Ddd/s7VM53oF9hcQQOXrevaJL4jFMNcGyK6LKJ0e7f7P+ +LNjzQG0qTX4wC/G8f8LHjS7NlevuW8MEo6hF13Twz4+e38VQS9y2DNwOgV373pfDhBQ21OdQK2u U1RyLd6tVMyb2gUoeizShPpUttmHHlGxplEziN77H7QGqlfzXekd7keBhWa/K8j8ANGwQsl+Q/wn 8S7lkxBPPYZcOWTXKpJplKLAwG8NHCeajH5A3Bwd2M03G2kK4RDADkvrAVinYeCvyk4k+nkJg64t vFArhFodrmkz6hP/VFdYfo4WTKnYyb6inGxdx014SK1c2LXihla8healWQ== X-Report-Abuse-To: spam@filterapi.hostcontrol.com This is a multipart message in MIME format. ------=_NextPart_000_0023_01D45913.E0ACF8F0 Content-Type: text/plain; charset="us-ascii" Content-Transfer-Encoding: 7bit ------=_NextPart_000_0023_01D45913.E0ACF8F0 Content-Type: text/html; charset="us-ascii" Content-Transfer-Encoding: quoted-printable 
 
------=_NextPart_000_0023_01D45913.E0ACF8F0--

**Comment by Slamdunk** [comment]
Well it is clear that the email you received has an empty `To` header, and a non valid email `From` header, so the value you get from this library are corrects

**Comment by martin-schaap** [comment]
This seems an issue with the mail hosting provider. Checked 2 domains and all mail have the same issue. I'm afraid provider is not going to solve this...

**Comment by martin-schaap** [comment]
Strange thing is that I have the same with a Googlemail account. I would not expect that.

**Comment by PiVSS** [comment]
Same here with G-Suite account, don't check with another provider for the moment.

getFrom() , getSender() and getTo() are always empty.
But getHeaders() is ok and the fields (to, from, replay, sender etc.) correctly populated.

My 2 cents

**Comment by Slamdunk** [comment]
@PiVSS can you upload here a raw message that has this issue?

**Comment by PiVSS** [comment]
@Slamdunk Thanks for your help

All my messages have the issues.
From and To  field from the raw messages are correctly populated.
The header of each message have correct to/send/from fields.

Maybe I'm just using the wrong way.
I checked how the class EmailAddress works and in fact I need to use function getAddress or getFullAddress to have the information.

I was trying to get the from address with $message->getFrom().
In fact i need to use $message->getFrom()->getAddress();
That's right ?

Same way to get Sender and To information
foreach ($message->getSender() as &$value) echo $value->getFullAddress();
foreach ($message->getTo() as &$value) echo $value->getFullAddress();

Right ?

**Comment by Slamdunk** [comment]
@PiVSS note there is no need for the reference operator `&`: in PHP all objects are passed by reference.

Yes, `getAddress` or `getFullAddress` should return something, but are filled differently depending on the mail server

**Comment by PiVSS** [comment]
@Slamdunk Thanks you and sorry for disturbing.

Maybe a stupid question but, why the function getSender() needs to return an array ?
That's logical for To, Cc, Bcc fields as they can be multiples.
But the Sender is not supposed to be unique ?

**Comment by Slamdunk** [comment]
>  But the Sender is not supposed to be unique ?

Yes, it is **SUPPOSED** to be unique, but there is no univeral blocking standard that dumps multiple Sender header, although it's hard to find one today.

**Comment by PiVSS** [comment]
Copy that.
Thank you for your time.
