### ISSUE TITLE
ERROR: Message "xxx" has invalid headers

### ISSUE THREAD

**Issue by adrianet86** [ddeboer/imap#375]
Hello,
I am facing this issue when I read emails from method **getMailbox()**
It happens randomly and I don't know why. If I run the code again with the same emails, it works.

> Message "8569" does not exist
imap_alerts (0):
imap_errors (0):PHP Warning:  imap_headerinfo(): Bad message number in /app/vendor/ddeboer/imap/src/Message.php on line 155
PHP Stack trace:
PHP   1. {main}() /app/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /app/bin/console:29
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:248
PHP   6. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
PHP   7. P2PBundle\Command\Affiliate\ProcessAffiliateEmailsSymfonyCommand->run() /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:964
PHP   8. P2PBundle\Command\Affiliate\ProcessAffiliateEmailsSymfonyCommand->execute() /app/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
PHP   9. Gindumac\Affiliate\Command\ProcessNewIncomingAffiliateEmailsCommandHandler->handle() /app/src/P2PBundle/Command/Affiliate/ProcessAffiliateEmailsSymfonyCommand.php:49
PHP  10. Gindumac\Affiliate\Command\ProcessNewIncomingAffiliateEmailsCommandHandler->outputDebug() /app/src/Gindumac/Affiliate/Command/ProcessNewIncomingAffiliateEmailsCommandHandler.php:87
PHP  11. Ddeboer\Imap\Message->getFrom() /app/src/Gindumac/Affiliate/Command/ProcessNewIncomingAffiliateEmailsCommandHandler.php:102
PHP  12. Ddeboer\Imap\Message->getHeaders() /app/vendor/ddeboer/imap/src/Message/AbstractMessage.php:42
PHP  13. imap_headerinfo() /app/vendor/ddeboer/imap/src/Message.php:155
ERROR: Message "8569" has invalid headers
imap_alerts (0):
imap_errors (0):

Here the code I use.

`public function __construct($config)
    {
        $email = $config['email'];
        $pass = $config['pass'];
        $hostname = $config['hostname'];
        $this->mailboxRead = $config['mailbox_read'];
        $this->mailboxProcessed = $config['mailbox_processed'];

        $server = new Server($hostname);

        /** @var Connection $connection */
        $this->connection = $server->authenticate($email, $pass);
    }

    public function readEmails()
    {
        $mailbox = $this->connection->getMailbox($this->mailboxRead);
        $messages = $mailbox->getMessages();

        return $messages;
    }`

When I get message from readEmails and I loop them, in one of them stops with the previous output message error.

Any idea? Thanks

**Comment by Slamdunk** [comment]
The `getMessages()` fetches the message numbers, and only when you iterate the *n*-th message it fetches the *n*-th message. So it is possible to have this error if en email disappears from the mailbox between the first `getMessages()` call and its iteration, for example when the mail is deleted or moved.

**Comment by Slamdunk** [comment]
Maybe: I would like to ask you to search and find the originator of the issue: only then I can do something in this library.
