### ISSUE TITLE
How to fetch only UNSEEN emails?

### ISSUE THREAD

**Issue by mbsmt** [ddeboer/imap#376]
I couldn't find any option to fetch only UNSEEN emails from mail boxes. Is there such feature in this code?
Up to now, I think this package loads all emails and then programmer needs to use `$message->isSeen()` to determine is that email an UNSEEN one or not. In this case, the total time for loading emails might be high.

**Comment by Slamdunk** [comment]
As written in the README.md, chapter [Searching for Messages](https://github.com/ddeboer/imap#searching-for-messages), you can use flags for this:

```php
$messages = $mailbox->getMessages(new \Ddeboer\Imap\Search\Flag\Unseen());
```

**Comment by mbsmt** [comment]
I used your recommendation. This is the current error message:
`Argument 1 passed to Ddeboer\Imap\Mailbox::getMessages() must be an instance of Ddeboer\Imap\SearchExpression, instance of Ddeboer\Imap\Search\Flag\Unseen given`

**Comment by Slamdunk** [comment]
Your error shows you are not using the latest version, which is as the date of this comment [1.5.5](https://packagist.org/packages/ddeboer/imap)

**Comment by mbsmt** [comment]
@Slamdunk, I installed a fresh copy of your project and still I have that problem!

**Comment by Slamdunk** [comment]
What PHP version are you using?

**Comment by mbsmt** [comment]
Oops. It might be the cause. I did not pay attention to required PHP version. I am using PHP 5.6.x
Do you think it is only because of difference in PHP version?

**Comment by Slamdunk** [comment]
Sure: your error refers to 0.5.2 version, and we maintain only the latest version, 1.5.5 as today, and as you can see in the [packagist page](https://packagist.org/packages/ddeboer/imap) it requires `php: ^7.0`

**Comment by mbsmt** [comment]
You are right @Slamdunk. Thank you for your replies.
