### ISSUE TITLE
PHP's error handler is not restored if `loadStructure` fails

### ISSUE THREAD

**Issue by akinofftz** [ddeboer/imap#377]
In `Message::loadStructure()` the default error handler is overwritten in order to throw a `MessageDoesNotExistException`. It's restored after fetching the message, but if that fails, the error handler is never restored, so after this point, _any_ PHP error causes throwing a `MessageDoesNotExistException`.

**Comment by Slamdunk** [comment]
I don't really get your references: there is no `throw` before the `restore_error_handler` call:

https://github.com/ddeboer/imap/blob/89e0ea51722c3a9ea7e9c4aa4647ede981434cc4/src/Message.php#L69-L80

Could you please elaborate better the bug, or sharing a snippet of code to reproduce it?

**Comment by akinofftz** [comment]
Okay, checked again. Seems that we are using v0.5.2 in our project. So this error is caused by outdated version. Have to check our dependencies. Sorry.
