### ISSUE TITLE
Fetch attachment details (size, MIME type, etc.) before file_put_contents

### ISSUE THREAD

**Issue by mbsmt** [ddeboer/imap#379]
For security and controlling issues, is it possible to access the attachment file details like Size, MIME Type, Width, Height, etc. before using `file_put_contents` ? If it is possible, please guide me to find its appropriate documents.

**Comment by Slamdunk** [comment]
Hi, I don't get what you intend for `file_put_contents`: there is no such call in this library.

Can you explain better your use case?

**Comment by mbsmt** [comment]
https://github.com/ddeboer/imap#message-attachments

`
$attachments = $message->getAttachments();

foreach ($attachments as $attachment) {
    // getDecodedContent() decodes the attachment’s contents automatically:
   file_put_contents(
       '/my/local/dir/' . $attachment->getFilename(),
       $attachment->getDecodedContent()
   );
}

`

**Comment by Slamdunk** [comment]
In your original post you cite `MIME Type, Width, Height`, so I suppose you are talking about an Image attachment.
This library only sticks to the email standards, it's attachment agnostic, so you have to fetch the decoded content of it and use your own logic to do further checks

**Comment by mbsmt** [comment]
Thank you @Slamdunk
