### ISSUE TITLE
Problems running latest version

### ISSUE THREAD

**Issue by codepixel** [ddeboer/imap#384]
Hello
I’ve download the latest version from GitHub but when trying to run I got the following error:
Uncaught TypeError: Return value of Ddeboer\Imap\ImapResource::initMailbox() must be an instance of Ddeboer\Imap\void, none returned in 

I’ve installed in the first time through composer and it install version 0.5x and it worked. No error occurred.

Now I want the lastest files from repository and once I copied the new files and tried to run I got this error.

```php
require_once( $_SERVER['DOCUMENT_ROOT'] . '/_inc/vendor/Ddeboer/autoload.php');

use Ddeboer\Imap\Server;
use Ddeboer\Imap\SearchExpression;
use Ddeboer\Imap\Search\Email\To;
use Ddeboer\Imap\Search\Text\Body;
use Ddeboer\Imap\Search\Date\After;
use Ddeboer\Imap\Message\Headers; 

$username = 'my mail address';
$password = 'my password';
$server = new Server('imap.gmail.com',993,"/imap/ssl/novalidate-cert");
$connection = $server->authenticate($username, $password);

$mailboxes = $connection->getMailboxes();
```

Can you please help me.

Thanks in advanced
Bruno

**Comment by Slamdunk** [comment]
What PHP version are you using and what this library version do you installed?

**Comment by goncalogoncalves** [comment]
I had this problem with PHP version 7.0.4.

Changed to version 7.2.3 and now it works.
