### ISSUE TITLE
I need an autoload.php

### ISSUE THREAD

**Issue by Shamim1977** [ddeboer/imap#397]
Hi,

I am not using composer (my mac is raising disgusting errors with composer).
Here is my app structure-

index.php (this is initiating Ddeboer/Imap)
-Ddeboer
--Imap
.... .... ...

Placed these lines on top of index.php-
use Ddeboer\Imap\Server;
use Ddeboer\Imap\SearchExpression;
use Ddeboer\Imap\Search\Email\From;
use Ddeboer\Imap\Search\Email\To;
use Ddeboer\Imap\Search\Text\Subject;
use Ddeboer\Imap\Search\Text\Body;
use Ddeboer\Imap\Search\Flag\Unseen;

And than-
require_once 'Ddeboer/Imap/Server.php';
require_once 'Ddeboer/Imap/SearchExpression.php';
require_once 'Ddeboer/Imap/Search/Email/From.php';
require_once 'Ddeboer/Imap/Search/Email/To.php';
require_once 'Ddeboer/Imap/Search/Text/Subject.php';
require_once 'Ddeboer/Imap/Search/Text/Body.php';
require_once 'Ddeboer/Imap/Search/Flag/Unseen.php';

And calling it like this-
$server = new Server('imap.gmail.com', '993');
$connection = $server->authenticate(INBOX_TO_READ, PASSWORD);
//$mailboxes = $connection->getMailboxes();
$mailbox = $connection->getMailbox('INBOX');

$search = new SearchExpression();
$search->addCondition(new From(SOME_SENDER);
$search->addCondition(new Unseen());
$messages = $mailbox->getMessages($search);

But I am always getting the following error-
**Interface 'Ddeboer\Imap\ServerInterface' not found in /home/fhbmachine/public_html/gmonitor/Ddeboer/Imap/Server.php on line 13**

I even tried adding the following line in the Server.php file-
use Ddeboer\Imap\ServerInterface;

No luck.

Please suggest.

**Comment by Slamdunk** [comment]
This project follows the PSR-4 standard, so there is a 1:1 map between classname and filename. Simply `require_once 'Ddeboer/Imap/ServerInterface.php';`

By the way, we only support composer autoloading.

**Comment by Shamim1977** [comment]
Thanks for the quick reply. Appreciate it.
Can u pls share a copy of the autoload.php file? I am having trouble generate it here.
