### ISSUE TITLE
20 secondes to extract 20 emails. 

### ISSUE THREAD

**Issue by ronlinet** [ddeboer/imap#418]
I have tested the package on an email box with 20 emails and it takes about 10 seconds to connect and 20 seconds to show the harvested messages.    

```php
        $server = new Server('imap.gmail.com');
        $connection = $server->authenticate('myemail@email.com', 'pwd');

        $lastDay = $today->sub(new DateInterval('PT5M'));
        $messages = $mailbox->getMessages(
            new \Ddeboer\Imap\Search\Date\Since($lastDay),
            \SORTARRIVAL, // Sort criteria
            true // Descending order
        );

        print_r( $messages );

```
I am using this emails to populate my real time info list and waiting 20 second to refresh the list is a bit long. Is there any way to narrow down the time for mail fetching to 1 / 3 seconds ?

**Comment by Slamdunk** [comment]
20 seconds is not usual, it doesn't depend on the library. Fetching the messages of the last year in the INBOX of my provider takes half a second:

```php
require __DIR__ . '/vendor/autoload.php';

$start = microtime(true);
$server = new \Ddeboer\Imap\Server('imap.provider.com');
$connection = $server->authenticate('my@email.com', 'xxx');

$mailbox = $connection->getMailbox('INBOX');
$lastDay = (new DateTimeImmutable())->sub(new DateInterval('P1Y'));

$messages = $mailbox->getMessages(
    new \Ddeboer\Imap\Search\Date\Since($lastDay),
    \SORTARRIVAL, // Sort criteria
    true // Descending order
);

var_dump([$mailbox->getName(), count($messages)]);

$elapsed = microtime(true) - $start;
var_dump(number_format($elapsed, 2, '.', '') . ' s');
```
Outputs:
```
$ php test.php 
array(2) {
  [0]=>
  string(5) "INBOX"
  [1]=>
  int(25)
}
string(6) "0.58 s"
```
If I also retrieve the full content of that 20 messages, the script take 1 second and a half, so 20 seconds don't seem an issue of this library.

**Comment by ronlinet** [comment]
Thank you for the feedback @Slamdunk , I will focus my research on the configuration / provider side.
