### ISSUE TITLE
Installation without composer

### ISSUE THREAD

**Issue by PlutoHDDev** [ddeboer/imap#420]
Is it possible to use the library without composer? I have a webserver hosted by an external provider and I cannot use composer.

**Comment by Slamdunk** [comment]
If you download the source and write you own [PSR-4: Autoloader](https://www.php-fig.org/psr/psr-4/), yes, but nothing out-of-the-box

**Comment by pyatnitsev** [comment]
@PlutoHDDev, I think, you can use composer localy, download the library, and after it, upload to your hosting all files. You don't use composer in hosting but it do some work for you. 

Hope it helps.

**Comment by Slamdunk** [comment]
You can have a look at tools like [Deployer](https://github.com/deployphp/deployer) to upload packaged source

**Comment by lukasdoerr** [comment]
How about downloading it local on your machine and uploading it then?

**Comment by tuptuptup** [comment]
Version from https://php-download.com/package/ddeboer/imap works well.
