### ISSUE TITLE
How to create an instance of MessageInterface from EML object

### ISSUE THREAD

**Issue by pyatnitsev** [ddeboer/imap#434]
Hi!

Is there any way to create Message class or MessageInterface object from saved eml object or it's only possible with IMAP connection? 

Thanks.

**Comment by Slamdunk** [comment]
Duplicate of #265 : as said there, it is possible but no one as of yet is working on this feature.

Any PR is welcome though :+1:

**Comment by pyatnitsev** [comment]
ok, I will take a look on #265. Lets continue feature discuss in there. 

Thanks.
