### ISSUE TITLE
Invalid Date header when trying to fetching date on not RFC compliant emails

### ISSUE THREAD

**Issue by pupaxxo** [ddeboer/imap#438]
Hi,

we saw a few messages using a date header like this 'Mon, 15 09 2014 05:25:04'. Of course this is not RFC-compliant. I don't know if it makes sense to add some sort of parsing.

Currently we are using a manual date reader to support these invalid formats.

**Comment by Slamdunk** [comment]
Hi, dates in email strictly follow the law of we-love-to-mess-everything-so-lets-shuffle.
This library is tested against the most common date formats: https://github.com/ddeboer/imap/blob/master/tests/MessageTest.php#L595

You can add that format to the test cases, and if the tests fail you can try to fix the algorithm, any PR is welcome
