### ISSUE TITLE
Is there a possibility for fetch an email by Id ?

### ISSUE THREAD

**Issue by frenchqwerty** [ddeboer/imap#456]
Hi,

Can I get an email by Id ?

Thanks

**Comment by lukasdoerr** [comment]
You need the Message ID. So just use getMessage(<ID>);

Ex:
`$messages1 = $mailbox->getMessage('1657');
   foreach ($messages1 as $message1) 
   {
      echo $message1->getFrom()->getAddress();
   }`

**Comment by lukasdoerr** [comment]
And you can get the ID with: $message->getNumber();

**Comment by frenchqwerty** [comment]
Hi, thank you for your reply. Have a nice day
