### ISSUE TITLE
getMessages() doesn't retrieve message from a Since object

### ISSUE THREAD

**Issue by frenchqwerty** [ddeboer/imap#457]
Hello,
I am trying to get the messages with Since object.

`today = new DateTimeImmutable();
        $lastHour = $today->sub(new DateInterval('PT2H'));
        $messages = $mailbox->getMessages(
            new Since($lastHour),
            \SORTARRIVAL,
            true
        );`

I cannot get the message since 2 hours for exemple... It's get the mails from today

**Comment by lukasdoerr** [comment]
Please check DateTimeImmutable. It's back in the game since php 7.3.x
