### ISSUE TITLE
[question] Does getBodyHtml() load html?

### ISSUE THREAD

**Issue by dieuz1** [ddeboer/imap#464]
Many companies track open rate using email image tracking. Does this library actually load the html when going through "getBodyHtml()"? If not, is there anyway to make it load the html so that this image pixel get loaded and it seems as the email was opened for real?

**Comment by Slamdunk** [comment]
> Does this library actually load the html when going through "getBodyHtml()"?

No

> If not, is there anyway to make it load the html so that this image pixel get loaded and it seems as the email was opened for real?

Yes, with a dedicated HTML parser and loader, not present in this very library though.
