### ISSUE TITLE
getThread and getMessageSequence not using with the same id

### ISSUE THREAD

**Issue by maisoui** [ddeboer/imap#469]
Hi,

I have a problem to retrieve the thread and sequence of the messages on the server because getThread uses sequence numbers but getMessageSequence uses UIDs instead of sequence numbers (according to FT_UID argument). For me, this is inconsistent, and I suggest two variants to fix it :

- use argument SE_UID in the following line $tree = \imap_thread($this->resource->getStream(), SE_UID);
- Add argument for both methods getThread and getMessageSequence 

I hope I was clear in my description.
Best regards

**Comment by Slamdunk** [comment]
Hi, I'd appreciate if you can propose a PR with the first solution, as it seems a bug indeed
