### ISSUE TITLE
Not able to access $message->getFrom() , Why it is private propert?

### ISSUE THREAD

**Issue by Dasinfomedia2** [ddeboer/imap#476]
I am not able to access most of the properties because it shows a private property.

```
object(Ddeboer\Imap\Message\EmailAddress)[1504]
  private 'mailbox' => string 'cpanel' (length=6)
  private 'hostname' => string 'xxxxx.com' (length=9)
  private 'name' => string 'cPanel on xxx.com' (length=19)
  private 'address' => string 'cpanel@xxxx.com' (length=16)
```

Is this a bug or am I doing it wrong?

**Comment by Slamdunk** [comment]
You can inspect how the class works by looking at its tests: https://github.com/ddeboer/imap/blob/master/tests/MessageTest.php#L313

**Comment by Dasinfomedia2** [comment]
@Slamdunk Thank you.
