### ISSUE TITLE
[QUESTION] Why does markAsSeen() not modify the Message it is called on?

### ISSUE THREAD

**Issue by markwatney2016** [ddeboer/imap#478]
As far as I can see calling `$myMessage->markAsSeen()` only marks the message/email on the IMAP server as read but not the PHP object `$myMessage`, right? Why is that an what is the recommended way to also mark the PHP object `$myMessage` as read?

**Comment by Slamdunk** [comment]
> As far as I can see calling `$myMessage->markAsSeen()` only marks the message/email on the IMAP server as read but not the PHP object `$myMessage`, right?

Wrong, the object gets its cache immediately expired and `isSeen()` returns the updated value, take a look at the test:

https://github.com/ddeboer/imap/blob/d439d09376dd53209788cddb6e2ea277f8ddc8a6/tests/MessageTest.php#L102-L114

**Comment by markwatney2016** [comment]
You are right. Thank you.
