### ISSUE TITLE
Error when get Message

### ISSUE THREAD

**Issue by vladislavtkachenko** [ddeboer/imap#485]
![image](https://user-images.githubusercontent.com/21283123/100982009-9b126400-3558-11eb-9165-2794e9b633d7.png)
![image](https://user-images.githubusercontent.com/21283123/100982027-a2d20880-3558-11eb-9d58-4839359ca702.png)

**Comment by Slamdunk** [comment]
Please provide extensive environment details and the full stack trace, otherwise how could I help you?

**Comment by vladislavtkachenko** [comment]
Ah, sorry

Laravel 8.17.0
PHP 8.0.0

![image](https://user-images.githubusercontent.com/21283123/100982496-2855b880-3559-11eb-867b-10ea16e7bd84.png)

**Comment by Slamdunk** [comment]
IMAP provider?

**Comment by vladislavtkachenko** [comment]
imap.yandex.ru

**Comment by Slamdunk** [comment]
Did it worked on PHP 7.4 and ddeboer/imap v5?

**Comment by vladislavtkachenko** [comment]
i'll check and answer...

**Comment by vladislavtkachenko** [comment]
php 7.4.12 - works correct

**Comment by Slamdunk** [comment]
I guess you're already on ddeboer/imap v1.11 on PHP8, right?

**Comment by vladislavtkachenko** [comment]
installed "ddeboer/imap": "^1.11"

**Comment by Slamdunk** [comment]
So, I have no idea where the bug is.

Every imap provider reinvent the wheel, so I'd need an account to run the test suite against in order to debug id.

But I can't speak Russian and cannot surf the website: may you create a `ddeboerimaptest` account, and send me the credentials to my email please?

**Comment by vladislavtkachenko** [comment]
I can grant access to my test account.
what's your email address?

**Comment by Slamdunk** [comment]
You can read it in my latest commit: https://github.com/ddeboer/imap/commit/922ee04883082501ebca2f0ae78e7b6e1c1fd4da.patch

**Comment by vladislavtkachenko** [comment]
I sent the account data to your email address

**Comment by Slamdunk** [comment]
So, I've run the test suite against the account, both with PHP 7.4 and PHP 8.0:

1. php7.4 vendor/bin/phpunit [yandex-php74.txt](https://github.com/ddeboer/imap/files/5635176/yandex-php74.txt)
1. php8.0 vendor/bin/phpunit [yandex-php80.txt](https://github.com/ddeboer/imap/files/5635180/yandex-php80.txt)

With lot of errors, so yandex doesn't seem to adhere to IMAP standards as Dovecot and GMail do.

BTW, the diff between the two runs is:

```diff
--- yandex-php74.txt    2020-12-03 10:53:24.027017496 +0100
+++ yandex-php80.txt    2020-12-03 10:53:24.067017610 +0100
@@ -13,7 +13,7 @@
 /mnt/data/repos-tessarotto/imap/tests/MessageTest.php:383
 
  Ddeboer\Imap\Tests\MessageTest::testAttachmentMustNotBeCharsetDecoded
-count(): Parameter must be an array or an object that implements Countable
+TypeError: count(): Argument #1 ($var) must be of type Countable|array, stdClass given
 
 /mnt/data/repos-tessarotto/imap/tests/MessageTest.php:1027
 /mnt/data/repos-tessarotto/imap/tests/MessageTest.php:903
@@ -50,6 +50,16 @@
  Ddeboer\Imap\Tests\MailboxTest::testDelete
 Failed asserting that exception of type "Ddeboer\Imap\Exception\ReopenMailboxException" is thrown.
 
+ Ddeboer\Imap\Tests\MailboxTest::testGetMessagesWithUtf8Subject
+Failed asserting that two strings are identical.
+--- Expected
++++ Actual
+@@ @@
+-'23'
++''
+
+/mnt/data/repos-tessarotto/imap/tests/MailboxTest.php:351
+
  Ddeboer\Imap\Tests\MessageTest::testFlags
 Failed asserting that two strings are identical.
 --- Expected
```

From which PHP 8.0 doesn't introduce new/different bugs.

The relevant test for your bug:

https://github.com/ddeboer/imap/blob/f71d65eab6fa938fbea337bb61783fb2801dd67b/tests/MessageTest.php#L318

is passing on both runs.

I'll try to get `ddeboer/imap` working on yandex as much as possible, but for now I can't help any further.

**Comment by vladislavtkachenko** [comment]
I noticed that only some messages get an error. At the same time, some of the messages are working correctly. But I don't see any dependency yet.. Thank you for your work

**Comment by vladislavtkachenko** [comment]
maybe you can do it.

`...->getMessages()` =  [
    0 => 1890
    1 => 1891
  ]
`
`
$connection->getMailboxes()['INBOX']->getMessage(1891)->getSubject();
`

**Comment by Slamdunk** [comment]
Can you elaborate it a bit? Do it expecting what instead of what?

**Comment by vladislavtkachenko** [comment]
I don't quite understand your question.. Sorry for my english)

**Comment by Slamdunk** [comment]
> maybe you can do it.
> $connection->getMailboxes()['INBOX']->getMessage(1891)->getSubject();

I can do this command against what IMAP server?
To obtain what result?

**Comment by vladislavtkachenko** [comment]
Using my test account for yandex

**Comment by vladislavtkachenko** [comment]
this may be a php bug

https://bugs.php.net/bug.php?id=80438

**Comment by Slamdunk** [comment]
Awesome, it seems that's the thing

**Comment by vladislavtkachenko** [comment]
I commented the \imap_msgno call in Message.php to manually specify the message id, the rest of the code worked correctly

**Comment by vladislavtkachenko** [comment]
Hi, @Slamdunk 

After upgrading to php 8.0.1, the problem is no longer there.
Perhaps you can close the issue if you don't need information about failed tests for yandex smtp

**Comment by pascualstromsnes** [comment]
@vladislavtkachenko I ended up here after experiencing the same problems, and I am able to replicate the error with PHP 8.0.1. I have also run the test that was enclosed with the PR that was merged to address this issue, and I am able to produce the same error there as in 8.0.1.

I see that there has been som additional changes in ext-imap for the 8.0.2RC2 and I will compile this during the weekend to see if this makes a difference, or if not I will file a new bug report.

There seems to be an ongoing discussion within the PHP core community about the possibility of dropping the support for a native IMAP extension developed by them, and instead make this a responsibility for the wider community to provide.

**Comment by pascualstromsnes** [comment]
@vladislavtkachenko  I have now compiled PHP v8.0.2RC1 (there is not RC2 yet, sorry about the typo in my previous post) on macOS Big Sur and ran a simple test suite testing these issues with the "Bad message no". Fortunately I can't see that the error occurs any more, so hopefully this means that coming 8.0.2 there will be no more problems with this issue.

And also @Slamdunk : thank you for providing such a well written package. I will make sure to star it and provide feedback if I see anything I can contribute. Cheers!

**Comment by vladislavtkachenko** [comment]
@pascualstromsnes @Slamdunk thank you

**Comment by gajosadrian** [comment]
I had this issue today on `PHP 8.0.0`. I read all your messages and #310 issue too.
My problem was that the last message from `MessageIterator` had invalid message number - just always the last message. I ended up by updating the PHP to `8.0.6` (last release) and the bug gone.

Thanks to @vladislavtkachenko for mentioning about this:
> this may be a php bug
> 
> https://bugs.php.net/bug.php?id=80438

I think that this issue is safe to close now.

**Comment by matthiasnoback** [comment]
Just ran into this as well and the library concealing the real PHP error in `Message::assertMessageExists()` has cost me several hours of debugging time. It's not your fault of course, but to prevent people from stumbling over this problem, can we somehow prevent people from using this library with PHP 8.0.0? E.g. add a conflicting version to composer.json?

**Comment by ddeboer** [comment]
Good suggestion @matthiasnoback! Done in #518.
