### ISSUE TITLE
Implement copyMove() function

### ISSUE THREAD

**Issue by tomsommer** [ddeboer/imap#494]
`imap_mail_move()` doesn't always work moving messages (Exchange has problems with it, for one), it would be nice with a `copyMove()` function that implements `imap_mail_copy()` with the `\CP_MOVE` option

Workaround currently looks like this:
`imap_mail_copy($imapConnection->getResource()->getStream(), (string) $_message->getNumber(), $imapMailbox>getEncodedName(), \CP_UID | \CP_MOVE);`

**Comment by Slamdunk** [comment]
Do you `expunge` the connection after moving the message?

**Comment by tomsommer** [comment]
Yes

**Comment by tomsommer** [comment]
I moved from https://github.com/tedious/Fetch/blob/master/src/Fetch/Message.php#L788 where move worked fine, because it uses `imap_mail_copy`

**Comment by Slamdunk** [comment]
Released in [v1.12.0](https://github.com/ddeboer/imap/releases/tag/1.12.0)
