### ISSUE TITLE
in the Readme

### ISSUE THREAD

**Issue by kmavroeidis** [ddeboer/imap#500]
README says  $connection->expunge(); which throws an error  
I used $mailbox->expunge(); and it expunges.

also, I had to do add the following line in the transcoder: 
if ($from=='auto') { $from =null; }

    public function transcode($string, $from = null, $to = null)
    {
        foreach ($this->transcoders as $transcoder) {
            try {
                if ($from=='auto') { $from =null; } // It was telling me the 'auto' is not supported.
                return $transcoder->transcode($string, $from, $to);
            } catch (UnsupportedEncodingException $e) {
                // Ignore as long as the fallback transcoder is all right
            }
        }
        
        throw $e;
    }

**Comment by Slamdunk** [comment]
From the code you've pasted it seems to me you are using an old version, which you didn't provided here as requested by the issue template.

Please be sure you are using the latest version (`v1.12` as of time of writing).
