### ISSUE TITLE
Inline images not as attachment

### ISSUE THREAD

**Issue by antoniofusco** [ddeboer/imap#502]
Hello
Is there a way to detect the inline images from the attachment list? If not would be better to have it
Thanks

**Comment by Slamdunk** [comment]
> Is there a way to detect the inline images from the attachment list?

Yes, check for the disposition and the type:

```php
'inline' === $attachment::getDisposition();
\Ddeboer\Imap\Message\PartInterface::TYPE_IMAGE === $attachment::getType();
```
