### ISSUE TITLE
Returns all emails on filter

### ISSUE THREAD

**Issue by nhCoder** [ddeboer/imap#503]
```
$today = new DateTimeImmutable();
$timeDel = $today->sub(new DateInterval('PT8M'));


$messages = $mailbox->getMessages(new Ddeboer\Imap\Search\Date\Before($timeDel));
```
I m trying to get emails received before 8 minutes ago but it returns all messages in INBOX.
Is this a bug or am I doing something wrong?
Any help will be appreciated .

**Comment by Slamdunk** [comment]
You should use the After filter

**Comment by nhCoder** [comment]
do you have an example

**Comment by nhCoder** [comment]
please have a look I have updated the whole question..

**Comment by nhCoder** [comment]
Does it support time based search.
i looked here and they say it doesn't support time based search https://stackoverflow.com/a/26791550

**Comment by Slamdunk** [comment]
>  i looked here and they say it doesn't support time based search https://stackoverflow.com/a/26791550

That may be true indeed.

I would suggest you to try one or a mix of there flags:

* `\Ddeboer\Imap\Search\Flag\Recent`
* `\Ddeboer\Imap\Search\Flag\Unseen`
* `\Ddeboer\Imap\Search\State\NewMessage`
