### ISSUE TITLE
Message replies

### ISSUE THREAD

**Issue by SylvanoTombo** [ddeboer/imap#509]
Hi, Is there a way to get replies for message?

**Comment by Slamdunk** [comment]
Is, with `Mailbox::getThread` method, see [`imap_thread`](https://www.php.net/manual/en/function.imap-thread.php) manual page for more infos.

**Comment by SylvanoTombo** [comment]
Hi @Slamdunk , thanks for your response. What i want to achieve is to search a specific message with `SearchExpression` after that i got a `Message` instance and i want to get the replies to this message. With `Mailbox::getThread()` i can't search for a specific message

**Comment by Slamdunk** [comment]
Look at https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.4 and https://bugs.php.net/bug.php?id=73640 with `HEADER` search command, but it highly depends on the provider if it's going to work or not.

**Comment by SylvanoTombo** [comment]
@Slamdunk , thanks! can you give me an example with the library please?
