### ISSUE TITLE
Using Getters

### ISSUE THREAD

**Issue by Nayazkaya** [ddeboer/imap#510]
Hello alll !

I have a problem using getters : 
```php
use Ddeboer\Imap\Server;
use Ddeboer\Imap\Message;

$server = new Server('ssl0.ovh.net');

// $connection is instance of \Ddeboer\Imap\Connection
$connection = $server->authenticate('**', '**');

$mailbox = $connection->getMailbox('INBOX');

$messages = $mailbox->getMessages();

foreach ($messages as $message) 
{
    $from = $message->getFullAddress();

}
```

The error is : 

`Fatal error: Uncaught Error: Call to undefined method Ddeboer\Imap\Message::getFullAddress() in`

Could somebody help me with this issues ?
Thanks a lot

**Comment by Slamdunk** [comment]
Hi, you first need to gather the address to apply `getFullAddress` to.

See tests for more examples:

https://github.com/ddeboer/imap/blob/f0e02bb82cdfbffa5c064be090e0b4c15edbf684/tests/MessageTest.php#L323-L333

**Comment by Nayazkaya** [comment]
Hi thank you a lot !!!
