### ISSUE TITLE
imap_reopen(): Couldn't re-open stream

### ISSUE THREAD

**Issue by tomsommer** [ddeboer/imap#522]
imap_reopen() can fail and trigger PHP's internal error handler

https://github.com/ddeboer/imap/blob/5f1d8ed40b365386c028e038658376410c59e8a8/src/ImapResource.php#L58

**Comment by Slamdunk** [comment]
Didn't know that, if you can provide a PR that handles this cause it would be awesome, maybe the at operator `@` is enough
