### ISSUE TITLE
You drop php 7.4 ?????

### ISSUE THREAD

**Issue by boily** [ddeboer/imap#528]
I was trying to update via composer ddeboer/imap dev-master.
You drop php 7.4 ???
- ddeboer/imap dev-master requires php ^8.0.1 -> your php version (7.4.3) does not satisfy that requirement.
I'm using ubuntu 20.4 with php 7.4.3, it seems to me a bit exagerated to drop v7.4 so early???
Is there any other alternative than migrating an entire php project to v8?
thanks
Roger

**Comment by Slamdunk** [comment]
> Is there any other alternative than migrating an entire php project to v8?

Yes, pick any:

1. follow SemVer and stick with v1.12.2 which supports php7.4 nicely
2. install the dep with `--ignore-platform-reqs`
3. fork the repo

> I'm using ubuntu 20.4 with php 7.4.3

I warmly invite you to use Sury packages to ensure you use latest version of php and be able to migrate php major version without updating the entire os
