### ISSUE TITLE
Question about the dates

### ISSUE THREAD

**Issue by webmake** [ddeboer/imap#529]
Hello,
I've noticed that
![image](https://user-images.githubusercontent.com/5016464/147477714-7f6978f9-e476-4487-a3d0-3d36c9ca7111.png)
our actual records (utc) when sent emails and emails when we received from the customers' replies datetimes mismatch.
And it seems related to the user's country, ex.: IT +1, SI +1, ML +0, GB +0.
Moreover, I've noticed some [cheats](https://github.com/ddeboer/imap/commit/337b65d94e430b3981f73ce08ae74ef47ed155cd) while parsing dates and other efforts [to fix date parsing](https://github.com/ddeboer/imap/commit/7418cf0ed9d3ead7c6bfb85ea25af7cd12792ee4). 
Question is, why don't you use udate headers? which would be simply `\DateTime::createFromFormat( 'U',$this->getHeaders()["udate"])` ?
As I see there is `date`, `maildate`, `udate` - three fields related with date and time..

**Comment by Slamdunk** [comment]
Hi, `MailDate` and `Udate` fields refer to the time the Imap server received or handled the first time the email.
It may be very different from the `Date` field of the mail itself, hence they cannot be used to represent the message `Date` header.
