### ISSUE TITLE
Google imap no longer supports username and password authentication.  

### ISSUE THREAD

**Issue by ronlinet** [ddeboer/imap#537]
Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.  => https://support.google.com/accounts/answer/6010255?hl=en . 

The standard client connection doesn’t work with imap.gmail.com anymore. 
 
```
$server     = new Server('imap.gmail.com', 993, '/imap/ssl/novalidate-cert' );
$connection = $server->authenticate('random@gmail.com', 'xxxxxxxxxxx'); 

```
What are now the guidelines to use this client with imap.gmail.com ?

**Comment by Slamdunk** [comment]
Rely on app passwords: https://support.google.com/mail/answer/185833

Duplicate of #109
