### ISSUE TITLE
Is there any way to add multiple 'oRcondition' in SearchExpression with From Address

### ISSUE THREAD

**Issue by AponAhmed** [ddeboer/imap#550]
I want to add search Expression by Multiple  From Address with OR condition

**Comment by Slamdunk** [comment]
You can use [`Ddeboer\Imap\Search\LogicalOperator\OrConditions`](https://github.com/ddeboer/imap/blob/master/src/Search/LogicalOperator/OrConditions.php) but beware of
https://github.com/ddeboer/imap#unknown-search-criterion-or
