### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by necmettin** [ddeboer/imap#552]
| Q | A
| --- | ---
| ddeboer/imap version | 1.14.2
| PHP version | 8.2.1
| IMAP provider | None

#### Summary

Library is not PHP 8.2 compatible

#### Current behavior

Produces deprecation warnings for dynamic property creation when running under PHP 8.2

#### How to reproduce: code & error stack trace

Try sending any email.
I've attached the output:
[php.log](https://github.com/ddeboer/imap/files/10371018/php.log)

#### Expected behavior

Not to produce any deprecation warnings.

**Comment by Slamdunk** [comment]
The log contains deprecations only from `mailchimp/transactional` package, which indeed has that issue:

https://github.com/mailchimp/mailchimp-transactional-php/blob/701b00f538f36a2a5b138f880ab5eebbfeff4b7d/lib/Api/UsersApi.php#L47-L52

**Comment by necmettin** [comment]
I'm sorry, I don't know why I reported it here :/
