### ISSUE TITLE
Imap Codeigniter 4

### ISSUE THREAD

**Issue by pitikkuning** [ddeboer/imap#554]
How to get Details Message Inbox on CodeIgniter 4?
My Code :
```php
public function readMail( this number of inbox mail )
{
    $getDetailsMessage     = $this->mailboxInbox->getMessage( this number of inbox mail );

    $data = [
        'title' => 'Baca Email Ci 4',
        'inbox' => $getDetailsMessage
    ];
    return view('readmail', $data);
}
```
I'm confused about how to retrieve the inbox number

**Comment by Slamdunk** [comment]
What do you mean by "inbox number"? The mailbox name or the message unique identifier?

**Comment by pitikkuning** [comment]
Problem Fixed by code :

**View :**

`<a href="<?= base_url() ?>/mailbox/baca-inbox/<?php $noMessage = $getMail->getNumber(); echo $noMessage; ?>"> Baca Email</a>     `                                                                                        

**Routes :**

`$routes->get('/mailbox/baca-inbox/(:num)', 'Mailbox::readMail/$1');`

**Controller :**

```
public function readMail($noMessage)
    {
        $getDetailsMessage     = $this->mailboxInbox->getMessage($noMessage);

        $data = [
            'title' => 'Baca Email Ci 4',
            'inbox' => $getDetailsMessage
        ];
        return view('readmail', $data);
    }
```

**_Thank you for participating in answering my questions._**
