### ISSUE TITLE
Authentication failed: [E_WARNING] Authentication failed for user "masoodahmad026@gmail.com": imap_open(): Couldn't open stream {imap.gmail.com:993/ssl} imap_alerts (0): imap_errors (1): - Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Invalid credentials (Failure)

### ISSUE THREAD

**Issue by masood313** [ddeboer/imap#571]
| Q                    | A                   |
|----------------------|---------------------|
| ddeboer/imap version | x.y.z               |
| PHP version          | x.y.z               |
| IMAP provider        | Like imap.gmail.com |

**Comment by longthanhtran** [comment]
I got the same problem today, and since the underline php imap raises the exception then [this](https://stackoverflow.com/questions/76004233/fetch-mails-from-gmail-account-using-php-imap) me the hint to solve. It's `app passwords` or `less secure app` but google will soon phase out those options
