### ISSUE TITLE
"date" header is not reliable

### ISSUE THREAD

**Issue by perk11** [ddeboer/imap#63]
Sometimes `date` header is not in a proper format, for example, mail.ru returns this for `date` header: `=?utf-8?B?0fAsIDQg4OLjIDIwMTAgMTM6MDE6NDAgKzAzMDA=?=`
This makes library fail in file `Header.php` on line 33. Using `maildate` from headers array instead solved it for me, but I'm not sure if this is a right way to do this.

**Comment by ddeboer** [comment]
Has this been fixed in 49b62f0b47377567e43e3d62518ac1125c22cf24?

**Comment by Slamdunk** [comment]
Can you post here the original raw message that gets you this behavior please?

**Comment by KundKMC** [comment]
EML File looks like this:

`Return-Path: <ZZZ@MAIL.COM>
X-Spam-Checker-Version: SpamAssassin 3.3.1 (2010-03-16) on SERVER
X-Spam-Level: ***
X-Spam-Status: No, score=3.0 required=5.0 tests=HTML_MESSAGE,MISSING_DATE,
	RCVD_IN_BRBL_LASTEXT,SPF_PASS,T_FRT_CONTACT autolearn=no version=3.3.1
X-Original-To: XXX@MAIL.COM
Delivered-To: YYY.MAIL.COM
Received: from SERVER (HOST [IP])
	by SERVER (Postfix) with SMTP id ID
	for <XXX@MAIL.COM>; Wed, 19 Jun 2013 14:49:53 +0200 (CEST)
Message-ID: <MSGID>
To: XXX@MAIL.COM
From: XXX@MAIL.COM
Subject: HEADLINE
Content-Type: multipart/alternative;
 boundary="______BoundaryOfDocument______"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

--______BoundaryOfDocument______
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
CONTENT

--______BoundaryOfDocument______
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: 7bit

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>CONTENT
</body>
</html>


--______BoundaryOfDocument______--

`

**Comment by Slamdunk** [comment]
Well in this email the Date header misses completely, there is no `maildate` header neither.

How could your fix https://github.com/KundKMC/imap/commit/2a7fb4a3c04a48e7cfee0452db134b1c04b7f4c3 work?

**Comment by KundKMC** [comment]
I just saw that. I'll get a raw copy from the server. Crazy clients ;)

**Comment by KundKMC** [comment]
You are right, there is not Header Field. But this code gets the job done: 

` try {
                $date = $message->getDate();
            } catch (\Throwable $ex) {
                die("FAIL:(");
            }

            if ($date == null) {
                $alteredValue = $message->getHeaders()->get('maildate');
                $alteredValue = \str_replace(',', '', $alteredValue);
                $alteredValue = \preg_replace('/^[a-zA-Z]+ ?/', '', $alteredValue);
                $alteredValue = \preg_replace('/ +\(.*\)/', '', $alteredValue);
                $alteredValue = \preg_replace('/\bUT\b/', 'UTC', $alteredValue);
                if (0 === \preg_match('/\d\d:\d\d:\d\d.* [\+\-]\d\d:?\d\d/', $alteredValue)) {
                    $alteredValue .= ' +0000';
                }
                try {
                    $date = new \DateTimeImmutable($alteredValue);
                } catch (\Throwable $ex) {
                    throw new InvalidDateHeaderException(\sprintf('Invalid Date header found: "%s"', $dateHeader), 0, $ex);
                }
            }
`
$date is 2013-06-19 14:49:55 with that E-Mail.
Mybe the field is set by the so called "fix" from 2015?

**Comment by Slamdunk** [comment]
The only possibility for your snippet to work is the presence of a `Maildate` header.

I can only help with the original raw message :disappointed:

**Comment by KundKMC** [comment]
Okay. I put some offort in it and it seems to work both ways:

[mail.eml.gz](https://github.com/ddeboer/imap/files/2629571/mail.eml.gz)

```
$mbox = "TESTCASE" . time();
$imap->createMailbox($mbox);
$mailbox = $imap->getMailbox($mbox);
$mailbox->addMessage(file_get_contents("/tmp/mail.eml"));
$messages = $mailbox->getMessages();
foreach ($messages as $message) {
    try {
        $date = $message->getDate();
    } catch (\Throwable $ex) {
        $date = new DateTimeImmutable("2009-01-02T00:00:00+0100");
    }
    if ($date == null) {
        var_dump($message->getHeaders()->get('maildate'));
    }
}

```
Creates a mailbox, uploads the EML File and shows:

string(26) "29-Nov-2018 15:46:40 +0100"

WTF!? It seems that there is some ReWriting going on, even while creating a message.

**Comment by Slamdunk** [comment]
Yup, it seems there an overwrite. It is likely that it happens only when querying the server through IMAp protocol, and the email remains untouched.
