### ISSUE TITLE
imap_fetchstructure sometimes returns encoding 6 and it is not present in Part::$encodingsMap

### ISSUE THREAD

**Issue by perk11** [ddeboer/imap#64]
I couldn't find any information what this encoding means. [PHP doc](http://php.net/manual/en/function.imap-fetchstructure.php) says encoding "may vary with used library".

I'm using `IMAP c-Client Version => 2007f` coming with PHP 5.5 for Windows distribution and I get this encoding sometimes. This throws error since there is no such item in Part::$encodingsMap array.

**Comment by mrtimp** [comment]
I've had some time tonight to investigate further.  I must say that i'm conflicted on what the right thing to do here is. Part of me thinks in the real-world you need to work round quirks with broken email messages to ensure that it doesn't impact your ability to work with 'all email messages' and the other part of me thinks that you should reject them if they are invalid.

I'm more than happy to do a PR if the developers feel its something of value.

Either way, here is a diff of my changes to fix my scenario:

Index: src/Ddeboer/Imap/Message.php
===================================================================
--- src/Ddeboer/Imap/Message.php	(revision 2802)
+++ src/Ddeboer/Imap/Message.php	(working copy)
@@ -306,6 +306,23 @@
     protected function loadStructure()
     {
         $structure = \imap_fetchstructure($this->stream, $this->messageNumber, \FT_UID);
+
+	    // look for an unknown character type encoding
+	    // to provide manual overrides if applicable
+	    if ($structure->encoding > 5) {
+		    $headers = \imap_fetchheader($this->stream, $this->messageNumber, \FT_UID);
+
+		    // match the character type encoding header to apply
+		    // any additional manual fixups or overrides
+		    if (preg_match('/^Content-Transfer-Encoding: (.*)$/im', $headers, $matches)) {
+			    $matches[1] = trim(preg_replace('/\s+/', '', $matches[1]));
+
+			    // pattern match other content type encoding that needs
+			    // to be manually remapped to another encoding type
+			    if ($matches[1] == 'quoted-printable') $structure->encoding = 4;
+		    }
+	    }
+
         $this->parseStructure($structure);
     }
 }
\ No newline at end of file

**Comment by mrtimp** [comment]
@perk11 I would be interested to see messages that were returning values 7-10 from imap_fetchstructure if you have any examples.

**Comment by perk11** [comment]
@mrtimp I'm not sure how to get full message text from debugger, here is structure of one of these messages: http://imgur.com/SAX4O97

**Comment by perk11** [comment]
So I went to trouble of logging ALL messages from the troubled account and interesting enough I failed to get encoding values greater than 6 in Message::loadStructure(), I only get them in Part::parseStructure(). I'm not sure how this is even possible, but this is what happens.

**Comment by Slamdunk** [comment]
Without examples and testable data, we can't do better than throw exception in case of unknown encoding, implemented in https://github.com/ddeboer/imap/pull/197.

@mrtimp we can implement manual look up for `Content-Transfer-Encoding`, but only with examples and enviroments variables:

1. What is the message full body?
1. What is the IMAP server and configuration?

As soon as we'll have all this info, we'll adapt the code. Until that time, we'll stick with throwing an exception.

Thank you all for the feedbacks.
