### ISSUE TITLE
imap_open error 

### ISSUE THREAD

**Issue by carlituxman** [ddeboer/imap#72]
I have this error using on laravel:

Authentication failed for user xxxxxx with error imap_open() expects at most 5 parameters, 6 given

**Comment by ddeboer** [comment]
`imap_open` has 6 parameters since PHP 5.3.2. Do you happen to be on an older PHP version?

**Comment by carlituxman** [comment]
I'm using on laravel homestead (vagrant box) with php version PHP 5.6.3

**Comment by ddeboer** [comment]
That is very weird, as this library is tested against PHP 5.6.

Can you debug [Server.php](https://github.com/ddeboer/imap/blob/master/src/Server.php#L80) to see with which parameters `imap_open()` is called? What happens if you call `imap_open()` yourself?

**Comment by carlituxman** [comment]
the problem is only on homestead.  I don't use it then.
