### ISSUE TITLE
A method to run IMAP commands?

### ISSUE THREAD

**Issue by mrcasual** [ddeboer/imap#83]
Is there a way I can run something like ```FETCH 1 (X-GM-MSGID)```?

**Comment by ddeboer** [comment]
As far as I can see, the IMAP extension has no way to run custom IMAP commands, so we would have run them over sockets. Maybe have a look at how https://github.com/petewarden/handmadeimap does this. Would you be able to work on a PR for this?

**Comment by mrcasual** [comment]
I'll take a look at it. Before, I've been using Zend's IMAP and it allows one to do something like ```protocol->requestAndResponse(command)```.
