### ISSUE TITLE
keepUnseen not working correctly with Hotmail

### ISSUE THREAD

**Issue by zachnoren** [ddeboer/imap#84]
Trying to use the following sample code with hotmail:
$message->keepUnseen()->getBodyHtml();

It is not keeping the messages as unread. Tried forcing a boolean in keepUnseen
$message->keepUnseen(true)->getBodyHtml();

Did not work. Tried forcing the class variable to be true by default on line 21 of Message.php, This also did not work.

**Comment by ddeboer** [comment]
Does Hotmail still exist? :confounded:

**Comment by zachnoren** [comment]
Yes it does. Not my choice. I am just the dev that has to work with it :/

**Comment by ddeboer** [comment]
I’m not sure why this wouldn’t work. Could you try to keep it unseen with PHP’s native IMAP functions?

**Comment by zachnoren** [comment]
Will try that tonight. I just tried with Gmail and I was able to replicate the issue there too.

**Comment by ddeboer** [comment]
Okay, let me know. We do have a [test](https://github.com/ddeboer/imap/blob/master/tests/MessageTest.php#L22) that should verify the keepUnseen behaviour on Gmail.

**Comment by zachnoren** [comment]
An update: Just ran the unit tests. I had 13 exceptions all the same thing
"Ddeboer\Imap\Exception\MailboxDoesNotExistException: Mailbox [Gmail]/Bin does not exist"

But I did have a failure in the Mark Unseen Test

There was 1 failure:

1) Ddeboer\Imap\Tests\MessageTest::testKeepUnseen
Failed asserting that false is true.
vendor/ddeboer/imap/tests/MessageTest.php:32
vendor/phpunit/phpunit/src/TextUI/Command.php:153
vendor/phpunit/phpunit/src/TextUI/Command.php:105

I tried this with my work email which is hosted with gmail. I will still try the PHP native functions later.

**Comment by zachnoren** [comment]
More information:

I have managed to put in a work around by modifying the line 319 in Part.php
https://github.com/ddeboer/imap/blob/master/src/Message/Part.php#L319

```php
protected function doGetContent($keepUnseen = true)
```
Forcing this true will keep the messages from being marked as read. Which works for my use case right now.

**Comment by Slamdunk** [comment]
Solved by https://github.com/ddeboer/imap/pull/95
