### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by nelu** [ddeboer/imap#85]
sorry to post here, new using your lib, but got this and something related on how to atleast fix it: https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/26

the bad part is that i got this exception while the message is being initialized, so no other operations can be performed on it (move delete), using getMessages() is not safe.

Encoding from `ks_c_5601-1987' to`UTF-8' is unsupported on this platform: iconv(): Wrong charset, conversion from `ks_c_5601-1987' to`UTF-8' is not allowed#0 [internal function]: Ddeboer\Transcoder\IconvTranscoder->Ddeboer\Transcoder{closure}(8, 'iconv(): Wrong ...', '/var/www/releas...', 38, Array)
#1 /vendor/ddeboer/transcoder/src/IconvTranscoder.php(38): iconv('ks_c_5601-1987', 'UTF-8', '[SUSPECTED SPAM...')

**Comment by cabloo** [comment]
@nelu I also have this issue all of a sudden, did you ever find a solution?

**Comment by Slamdunk** [comment]
Hi, can you provide the raw message headers?

Related to https://github.com/ddeboer/imap/issues/142

**Comment by Slamdunk** [comment]
Thank you for your help, the solution has been merged in https://github.com/ddeboer/imap/pull/196
