### ISSUE TITLE
preg replace error after called $message->getTo() and $message->getFrom()

### ISSUE THREAD

**Issue by dsouksavatd** [ddeboer/imap#87]
preg_replace(): Parameter mismatch, pattern is a string while replacement is an array after called $message->getTo() and $message->getFrom()

**Comment by Slamdunk** [comment]
Hi, can you provide the extended error stack trace?

**Comment by Slamdunk** [comment]
Closing due to unanswered updates.

Feel free to reopen the issue if needed.
