### ISSUE TITLE
Caching IMAP server connections

### ISSUE THREAD

**Issue by skynet** [ddeboer/imap#88]
Seems to be really slow connecting sometimes. TO what sort of extent is this caching connections to IMAP servers?

**Comment by miradnan** [comment]
+1

**Comment by Slamdunk** [comment]
IMAP connections should be started once per PHP process, what kind of caching do you propose?
Or is this fixable just with https://github.com/ddeboer/imap/issues/90?

**Comment by wujku** [comment]
Another way to keep IMAP connection alive is using a queue worker.
