### ISSUE TITLE
$message->getChildren()

### ISSUE THREAD

**Issue by zenderman** [ddeboer/imap#93]
Do not read the object $ message-> getChildren () how to use it?

**Comment by Lewiscowles1986** [comment]
This is in the readme.md of this very repo https://github.com/ddeboer/imap#messages... with no arguments it gets all messages from a mailbox. with optional search https://github.com/ddeboer/imap#searching-for-messages you can filter that list.

**Comment by Slamdunk** [comment]
Hi, can you explain the issue a bit more?

**Comment by Slamdunk** [comment]
Closing due to unanswered updates.

Feel free to reopen the issue if needed.
