### ISSUE TITLE
EmailAddress::__toString() fails if there the sender/recipient name contains a colon

### ISSUE THREAD

**Issue by vmattila** [ddeboer/imap#96]
Consider following From: header of a message `From: Something: Somewhere <example@example.com>`. When this kind of message is read, `PHP Catchable fatal error:  Method Ddeboer\Imap\Message\EmailAddress::__toString() must return a string value` is thrown.

It seems that PHP's native `imap_headerinfo()` parses this kind of address line incorrectly. When putting `print_r($value)` to the header parsing script `vendor/ddeboer/imap/src/Message/Headers.php` the output is:

```
Array
(
    [0] => stdClass Object
        (
            [mailbox] => Something
        )

    [1] => stdClass Object
        (
            [personal] => Somewhere
            [mailbox] => example
            [host] => example.com
        )

    [2] => stdClass Object
        (
        )

)
```

**Comment by ddeboer** [comment]
Thanks for the bug report. Are such From: headers valid? If so, would you like to open a PR to fix this?

**Comment by Slamdunk** [comment]
Yes such From header is valid, but the spaces should be escaped.

@vmattila can you provide the original raw message headers?

**Comment by vmattila** [comment]
I think I do not have the original message anymore to copy-paste the raw headers here.

As it has been a while since last update, I searched through the codebase and could not find `imap_headerinfo()` call anywhere. Before anybody gets confused as I was, must clarify that https://github.com/ddeboer/imap/blob/master/src/Message.php#L184 `imap_header()` is alias to `imap_headerinfo()` . ;)

**Comment by Slamdunk** [comment]
In https://github.com/ddeboer/imap/pull/199 we've put into test a standard complex email address:
https://github.com/ddeboer/imap/blob/aac8f581d3e636a69002a367379cb3996c5a6a3d/tests/fixtures/email_address.eml#L2
The format without the double-quotes is not valid and we can't do anything to fix it (except complex parsing of raw headers or throwing away the imap extension).
We have removed the `__toString()` function: use the `getAddress()` from now so at least you can catch handle graceful the error.
